import React, { createContext, useState, useEffect, useContext } from 'react';

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [language, setLanguageState] = useState('en');

    useEffect(() => {
        // Auto detect language on first load if not set
        const storedLang = localStorage.getItem('shapeup_language');
        if (storedLang) {
            setLanguageState(storedLang);
        } else {
            const browserLang = navigator.language || navigator.userLanguage;
            const defaultLang = browserLang.toLowerCase().includes('pt') ? 'pt-BR' : 'en';
            setLanguageState(defaultLang);
            localStorage.setItem('shapeup_language', defaultLang);
        }
    }, []);

    const setLanguage = (lang) => {
        setLanguageState(lang);
        localStorage.setItem('shapeup_language', lang);
    };

    const [unitSystem, setUnitSystemState] = useState(localStorage.getItem('shapeup_unit_system') || 'metric');

    const setUnitSystem = (unit) => {
        setUnitSystemState(unit);
        localStorage.setItem('shapeup_unit_system', unit);
    };

    // Helper: Safely converts a number assuming it was originally logged in one system, but we need it in another
    // defaultOrigin = 'metric' means "if we don't know what it was logged in, assume it was kg"
    const convertWeight = (value, originUnit = 'metric', targetUnit = unitSystem) => {
        const val = parseFloat(value);
        if (isNaN(val)) return 0;

        if (originUnit === targetUnit) return val;

        if (originUnit === 'metric' && targetUnit === 'imperial') {
            return val * 2.20462; // kg to lbs
        }
        if (originUnit === 'imperial' && targetUnit === 'metric') {
            return val / 2.20462; // lbs to kg
        }
        return val;
    };

    const formatWeight = (value, originUnit = 'metric') => {
        const converted = convertWeight(value, originUnit, unitSystem);
        // show 1 decimal place if it's not a whole number
        const formatted = converted % 1 === 0 ? converted.toString() : converted.toFixed(1);
        return `${formatted} ${unitSystem === 'imperial' ? 'lbs' : 'kg'}`;
    };

    // Dictionary for the Settings page and Sidebar
    const translations = {
        'en': {
            'nav.dashboard': 'Dashboard',
            'nav.clients': 'Clients',
            'nav.training_plans': 'Training Plans',
            'nav.my_training': 'My Training',
            'nav.exercises_library': 'Exercises Library',
            'nav.reports': 'Reports',
            'nav.feedback': 'Feedback',
            'nav.analytics': 'Analytics',
            'nav.settings': 'Settings',
            'nav.objectives': 'Objectives',
            'sidebar.chat': 'Chat with Coach',

            'pro.dashboard.title': 'Dashboard Overview',
            'pro.dashboard.subtitle': "Here's what's happening with your clients today.",
            'pro.dashboard.invite': 'Invite Client',
            'pro.dashboard.metric.active': 'Active Clients',
            'pro.dashboard.metric.active.sub': 'Total Active Portfolio',
            'pro.dashboard.metric.completed': 'Workouts Completed',
            'pro.dashboard.metric.completed.sub': 'Global 30-day Volume',
            'pro.dashboard.metric.skipped': 'Workouts Skipped',
            'pro.dashboard.metric.skipped.sub': 'Needs Attention',
            'pro.dashboard.metric.engagement': 'Avg. Engagement',
            'pro.dashboard.metric.engagement.sub': 'Platform Compliance',

            'pro.dashboard.feed.title': 'Global Client Activity Feed',
            'pro.dashboard.search': 'Search...',
            'pro.dashboard.filter.all': 'All Entries',
            'pro.dashboard.filter.workout': 'Workouts',
            'pro.dashboard.filter.message': 'Messages',
            'pro.dashboard.filter.alert': 'Alerts',
            'pro.dashboard.filter.system': 'System',
            'pro.dashboard.btn.clear': 'Clear',
            'pro.dashboard.feed.empty': 'No client activity found for these filters.',
            'pro.dashboard.feed.page': 'Page',
            'pro.dashboard.feed.of': 'of',
            'pro.dashboard.alerts.title': 'Client Alerts',
            'pro.dashboard.alerts.empty': 'All clients are currently on track.',
            'sidebar.logout': 'Log out',
            'header.role.pro': 'Professional',
            'header.role.client': 'Client',

            'clients.title': 'Client Management',
            'clients.subtitle': 'Directory of your active and inactive trainees.',
            'clients.invite': 'Invite New Client',
            'clients.search': 'Search clients...',
            'clients.filter': 'Filter',
            'clients.table.client': 'Client',
            'clients.table.plan': 'Active Plan',
            'clients.table.compliance': 'Compliance',
            'clients.table.checkin': 'Last Check-in',
            'clients.table.status': 'Status',
            'clients.table.actions': 'Actions',
            'clients.modal.delete.title': 'Delete Client?',
            'clients.modal.delete.body': 'will be permanently removed from your client list. This action cannot be undone.',
            'clients.modal.delete.cancel': 'Cancel',
            'clients.modal.delete.confirm': 'Delete Client',
            'clients.modal.toggle.title.act': 'Reactivate Client?',
            'clients.modal.toggle.body.act': '{{name}} will be restored to an active state and will regain access to their training plans.',
            'clients.modal.toggle.confirm.act': 'Reactivate Client',
            'clients.modal.toggle.cancel': 'Cancel',
            'clients.modal.toggle.title.inact': 'Suspend Client?',
            'clients.modal.toggle.body.inact': '{{name}} will be suspended. They will keep their data but lose access to active programs.',
            'clients.modal.toggle.confirm.inact': 'Suspend Client',
            'clients.invite.title': 'Invite New Client',
            'clients.invite.subtitle': "Send an invitation email to your client. They'll receive a link to create their ShapeUp account and connect with you.",
            'clients.invite.label': 'Client Email Address',
            'clients.invite.placeholder': 'client@example.com',
            'clients.invite.btn.cancel': 'Cancel',
            'clients.invite.btn.send': 'Send Invite',
            'clients.invite.error.empty': 'Please enter an email address.',
            'clients.invite.error.invalid': 'Please enter a valid email address.',
            'clients.invite.success.title': 'Invite Sent!',
            'clients.invite.success.desc': "An invitation has been sent to {{email}}. They'll receive an email with a link to join your coaching program.",
            'clients.invite.success.btn': 'Done',

            'clients.billing.title': 'Assign Billing Plan',
            'clients.billing.for': 'Configuring billing for:',
            'clients.billing.type.plan': 'Subscription Plan',
            'clients.billing.type.custom': 'Custom Rate',
            'clients.billing.plan.label': 'Select a Plan',
            'clients.billing.plan.empty': 'No subscription plans available. Go to Settings > Billing & Plan to create your tiers.',
            'clients.billing.custom.label': 'Custom Monthly Price ($)',
            'clients.billing.custom.help': 'This overrides regular subscription plans and bills this specific client a fixed monthly amount.',
            'clients.billing.btn.cancel': 'Cancel',
            'clients.billing.btn.apply': 'Apply Billing',

            'clients.status.active': 'Active',
            'clients.status.attention': 'Needs Attention',
            'clients.status.invited': 'Invited',
            'clients.status.inactive': 'Inactive',
            'pro.training.title.builder': 'Plan Builder',
            'pro.training.title.library': 'Training Library',
            'pro.training.subtitle.builder': 'Build reusable training templates and analyze structural volume.',
            'pro.training.subtitle.library': 'Manage your training templates and assign them to clients.',
            'pro.training.btn.create': 'Create New Plan',
            'pro.training.btn.back': 'Back to Library',
            'pro.training.empty.title': 'Your Template Library is Empty',
            'pro.training.empty.desc': 'Create reusable workout templates to easily assign structured training blocks to your clients.',
            'pro.training.empty.btn': 'Create First Plan',
            'pro.training.card.exercises': 'Exercises',
            'pro.training.card.sets': 'Sets',
            'pro.training.card.time': 'Est. Time',
            'pro.training.card.btn.edit': 'Edit Template',
            'pro.training.card.btn.assign': 'Assign to Client',
            'pro.training.assign.modal.title': 'Assign to Client',
            'pro.training.assign.modal.desc': 'Select a client to assign this template to:',
            'pro.training.assign.empty': 'No active clients found.',
            'pro.training.assign.success.title': 'Template Assigned',
            'pro.training.assign.success.message': 'The template has been successfully assigned to the client.',
            'pro.training.assign.success.btn': 'Great!',
            'pro.exercises.title': 'Exercise Library',
            'pro.exercises.subtitle': 'Browse and manage the global exercise database.',
            'pro.exercises.btn.suggest': 'Suggest New Exercise',
            'pro.exercises.search': 'Search exercises by name...',
            'pro.exercises.filter': 'Muscles',
            'pro.exercises.filter.header': 'Filter by Target Muscle',
            'pro.exercises.filter.clear': 'Clear Filters',
            'pro.exercises.empty': 'No exercises found matching your criteria.',

            'pro.feedback.title': 'Feedback & Inbox',
            'pro.feedback.subtitle': 'Review client check-ins, form videos, and direct messages.',
            'pro.feedback.search': 'Search messages...',
            'pro.feedback.empty.list': 'No messages yet.',
            'pro.feedback.ticket.action': 'Action Required',
            'pro.feedback.ticket.needs': 'Needs Attention: ',
            'pro.feedback.ticket.general': 'General Chat',
            'pro.feedback.btn.resolve': 'Mark Resolved',
            'pro.feedback.unread.new': 'New Messages Below',
            'pro.feedback.replying': 'Replying to ',
            'pro.feedback.you': 'You',
            'pro.feedback.attachment.doc': 'Message attachment',
            'pro.feedback.input.placeholder': 'Reply to ',
            'pro.feedback.input.btn': 'Send Reply',
            'pro.feedback.empty.thread.title': 'No Message Selected',
            'pro.feedback.empty.thread.desc': 'Select a conversation from the active feed to view details.',
            'pro.feedback.menu.reply': 'Reply to Message',

            'pro.analytics.title': 'Business Analytics',
            'pro.analytics.subtitle': 'Track your coaching business growth and overall client performance.',
            'pro.analytics.btn.export': 'Export Report',
            'pro.analytics.metric.mrr': 'Monthly Recurring Revenue',
            'pro.analytics.metric.mrr.trend': 'Based on Current Subscriptions',
            'pro.analytics.metric.clients': 'Active Clients',
            'pro.analytics.metric.clients.trend': 'Real-time Rosters',
            'pro.analytics.metric.adherence': 'Global Adherence',
            'pro.analytics.metric.adherence.trend': 'Computed from Active P.',
            'pro.analytics.metric.lifespan': 'Avg. Client Lifespan',
            'pro.analytics.metric.lifespan.unit': ' months',
            'pro.analytics.metric.lifespan.trend': 'Stable',
            'pro.analytics.chart.growth': 'Client Growth & Retention',
            'pro.analytics.chart.growth.active': 'Active Clients',
            'pro.analytics.chart.growth.churned': 'Churned',
            'pro.analytics.chart.adherence': 'Adherence Distribution',
            'pro.analytics.chart.adherence.clients': 'Clients',

            'pro.client.btn.message': 'Message Client',
            'pro.client.tabs.analytics': 'Analytics',
            'pro.client.tabs.plans': 'Training Plans',
            'pro.client.empty.analytics.title': 'No Data Available',
            'pro.client.empty.analytics.desc': "This client hasn't recorded any workout sessions yet. Analytics will appear once they complete a session.",
            'pro.client.chart.volume': 'Session Volume Trend',
            'pro.client.chart.rpe': 'Session RPE Trend (Effort)',
            'pro.client.chart.weight': 'Bodyweight Trend',
            'pro.client.chart.weight.empty': 'The client needs to log at least 2 weight entries in their Objectives tab to generate this trend.',
            'pro.client.chart.adherence': 'Adherence (Last 30 Days)',
            'pro.client.adherence.completed': 'Completed',
            'pro.client.adherence.skipped': 'Skipped',
            'pro.client.adherence.partial': 'Partial',
            'pro.client.chart.prs': 'Recent PRs & Improvements',
            'pro.client.prs.empty': 'No records broken yet.',
            'pro.client.prs.modal.title': 'PR:',
            'pro.client.prs.modal.desc': 'Comparing previous best vs new PR',
            'pro.client.prs.modal.prev': 'Previous Record',
            'pro.client.prs.modal.new': 'New Record',
            'pro.client.prs.modal.tag': 'NEW PR',
            'pro.client.plan.active': 'Active',
            'pro.client.plan.weeks': 'weeks',
            'pro.client.plan.exercises': 'exercises',
            'pro.client.plan.btn.edit': 'Edit',
            'pro.client.plan.btn.copy': 'Copy',
            'pro.client.plan.empty.ex': 'No exercises yet — click Edit to add some',
            'pro.client.plan.history.hide': 'Hide session history',
            'pro.client.plan.history.show': 'Show session history',
            'pro.client.plan.history.tag.partial': 'Partial',
            'pro.client.plan.history.tag.skipped.sess': 'Skipped Session',
            'pro.client.plan.history.tag.skipped.ex': 'Skipped Exercise',
            'pro.client.plan.delete.title': 'Delete Plan?',
            'pro.client.plan.delete.desc': 'will be permanently removed. This action cannot be undone.',
            'pro.client.plan.delete.cancel': 'Cancel',
            'pro.client.plan.delete.confirm': 'Delete Plan',
            'pro.client.plans.title': 'Assigned Plans',
            'pro.client.plans.btn.add': 'Add Plan',
            'pro.client.plans.empty': 'No plans assigned yet. Click "Add Plan" to create one.',

            'pro.builder.name': 'Plan Name',
            'pro.builder.weeks': 'Duration (Weeks)',
            'pro.builder.phase': 'Phase / Objective',
            'pro.builder.diff': 'Difficulty',
            'pro.builder.notes': 'General Plan Notes',
            'pro.builder.notes.ph': 'e.g. Focus on progressive overload over 6 weeks...',
            'pro.builder.stack': 'Exercise Stack',
            'pro.builder.add.ex': 'Add Exercise',
            'pro.builder.ex.name.ph': 'Exercise name',
            'pro.builder.ex.tags.ph': 'Tags e.g. Chest • Compound',
            'pro.builder.ex.notes.ph': 'Execution notes...',
            'pro.builder.set.type': 'Type',
            'pro.builder.set.tech': 'Technique',
            'pro.builder.set.reps': 'Reps',
            'pro.builder.set.load': 'Load %',
            'pro.builder.set.rpe': 'RPE',
            'pro.builder.set.rest': 'Rest (s)',
            'pro.builder.add.set': 'Add Set',
            'pro.builder.error.title': 'Duplicate Exercise',
            'pro.builder.error.duplicate': 'This exercise is already in the plan.',
            'pro.builder.error.btn': 'I Understand',
            'pro.builder.summary.title': 'Plan Summary',
            'pro.builder.summary.ex': 'Total Exercises',
            'pro.builder.summary.sets': 'Total Sets',
            'pro.builder.summary.sets.val': 'sets',
            'pro.builder.summary.time': 'Est. Duration',
            'pro.builder.summary.rpe': 'Avg RPE Target',
            'pro.builder.summary.phase': 'Phase',
            'pro.builder.summary.diff': 'Difficulty',
            'pro.builder.chart.intensity': 'Intensity Distribution',
            'pro.builder.chart.tech': 'Technique Usage',
            'pro.builder.btn.save': 'Save Plan',
            'pro.builder.btn.assign': 'Assign to Client',
            'pro.builder.btn.cancel': 'Cancel',

            'client.dashboard.welcome': 'Welcome back,',
            'client.dashboard.subtitle.nodata': 'Go to My Training to start your first session!',
            'client.dashboard.metric.weekly': 'Weekly Volume',
            'client.dashboard.metric.streak': 'Current Streak',
            'client.dashboard.metric.sessions': 'Sessions Completed',
            'client.dashboard.trend.weekly.nosessions': 'No sessions yet',
            'client.dashboard.trend.weekly.first': 'First week!',
            'client.dashboard.trend.streak.start': 'Start your streak!',
            'client.dashboard.trend.streak.great': '🔥 Great consistency!',
            'client.dashboard.trend.streak.keep': 'Keep it up!',
            'client.dashboard.trend.sessions.noplans': 'No plans assigned yet',
            'client.dashboard.trend.sessions.plans': 'Training plans',
            'client.dashboard.chart.title': 'Volume Progression',
            'client.dashboard.chart.nodata': 'Complete at least 2 sessions to see your volume trend.',
            'client.dashboard.achievements.title': 'Recent Improvements',
            'client.dashboard.achievements.nodata': 'Keep training and your improvements will appear here!',

            'client.training.title': 'Your Training Plans',
            'client.training.empty.title': 'No Plans Assigned',
            'client.training.empty.desc': "You don't have any training plans assigned to you yet.",
            'client.training.card.difficulty': 'Difficulty',
            'client.training.card.weeks': 'weeks',
            'client.training.card.exercises': 'Exercises',
            'client.training.card.btn': 'Start Session',
            'client.training.history.title': 'Session History',
            'client.training.history.empty': 'No completed sessions yet. Start a workout to build your history!',
            'client.training.history.vol': 'vol',
            'client.analysis.chart.vol': 'Total Vol (kg)',
            'client.analysis.chart.rpe': 'RPE (Difficulty)',
            'client.training.pagination.prev': 'Previous',
            'client.training.pagination.page': 'Page',
            'client.training.pagination.of': 'of',
            'client.training.pagination.next': 'Next',

            'client.session.btn.cancel': 'Cancel Session',
            'client.session.resting': 'Resting',
            'client.session.btn.skip': 'Skip',
            'client.session.modal.cancel.title': 'Cancel Workout?',
            'client.session.modal.cancel.desc': 'Are you sure you want to cancel this session? All progress and logged sets will be lost.',
            'client.session.modal.cancel.keep': 'Keep Training',
            'client.session.modal.cancel.confirm': 'Cancel Session',
            'client.session.modal.feedback.title': 'How did you feel today?',
            'client.session.modal.feedback.desc': 'Rate your overall session difficulty (RPE).',
            'client.session.modal.feedback.comments': 'Comments for Coach',
            'client.session.modal.feedback.placeholder': 'Any pain? Did you feel great? Leave a note...',
            'client.session.modal.feedback.submit': 'Submit Feedback',
            'client.session.modal.gamified.title': 'Workout Complete!',
            'client.session.modal.gamified.desc': 'Great job crushing',
            'client.session.modal.gamified.fallback': 'your workout',
            'client.session.modal.gamified.vol': 'Total Vol (kg)',
            'client.session.modal.gamified.duration': 'Duration',
            'client.session.modal.gamified.prs': 'New PRs',
            'client.session.modal.gamified.return': 'Return to Dashboard',
            'client.session.card.details': 'View Details',
            'client.session.table.set': 'Set',
            'client.session.table.target': 'Target',
            'client.session.table.rest': 'Rest',
            'client.session.table.weight': 'Weight',
            'client.session.table.reps': 'Reps',
            'client.session.table.rpe': 'RPE',
            'client.session.table.failure': 'Failure',
            'client.session.table.done': 'Done',
            'client.session.set_type.warmup': 'Warm-up',
            'client.session.set_type.feeder': 'Feeder',
            'client.session.set_type.working': 'Working',
            'client.session.set_type.topset': 'Top Set',
            'client.session.set_type.dropset': 'Drop Set',
            'client.session.set_type.backoff': 'Backoff',
            'client.session.btn.add_set': 'Add Extra Set',
            'client.session.btn.finish': 'Finish & Save Session',

            'client.exercise_modal.video': 'Official Execution Video',
            'client.exercise_modal.muscles': 'Targeted Muscles',
            'client.exercise_modal.notes.title': 'Execution Notes',
            'client.exercise_modal.notes.desc.1': 'This is a standardized placeholder description. To perform the ',
            'client.exercise_modal.notes.desc.2': ', ensure your form is consistent and you control the eccentric portion of the movement. Keep the selected ',
            'client.exercise_modal.notes.desc.3': ' stable throughout the range of motion.',
            'client.exercise_modal.notes.bullet1': 'Maintain core stability.',
            'client.exercise_modal.notes.bullet2': 'Follow a 2-1-1-0 tempo as a baseline.',
            'client.exercise_modal.notes.bullet3': 'Breathe out on the concentric phase.',

            'client.objectives.title': 'Your Objectives',
            'client.objectives.target.title': 'Target Goal',
            'client.objectives.target.label': 'Goal Weight (kg)',
            'client.objectives.target.btn': 'Update Goal',
            'client.objectives.target.saved': 'Goal Saved!',
            'client.objectives.log.title': 'Log Today\'s Weight',
            'client.objectives.log.label': "Today's Weight (kg)",
            'client.objectives.log.btn': 'Log Weight',
            'client.objectives.history.title': 'History',
            'client.objectives.history.empty': 'No weight entries logged yet.',
            'client.objectives.chart.title': 'Bodyweight Trend',
            'client.objectives.chart.empty': 'Log at least 2 weight entries to see your trend chart.',
            'client.objectives.chart.series.weight': 'Weight (kg)',
            'client.objectives.chart.series.goal': 'Goal Weight',

            'client.settings.notifications.title': 'Notification Preferences',
            'client.settings.notifications.chat.title': 'Chat Messages',
            'client.settings.notifications.chat.desc': 'Receive alerts when your coach sends you a direct message.',
            'client.settings.notifications.plan.title': 'Plan Updates',
            'client.settings.notifications.plan.desc': 'Push notification when your assigned training plan is modified.',
            'client.settings.notifications.system.title': 'System Reminders',
            'client.settings.notifications.system.desc': 'Platform updates, connection status, and automated check-ins.',

            'client.settings.billing.active.title': 'Active Subscription',
            'client.settings.billing.active.empty.title': 'No Plan Assigned',
            'client.settings.billing.active.empty.desc': 'Your coach has not assigned a billing plan to your account yet.',
            'client.settings.billing.payment.title': 'Payment Method',
            'client.settings.billing.payment.desc': 'Securely save your card details for automatic monthly billing.',
            'client.settings.billing.payment.card_num': 'Card Number',
            'client.settings.billing.payment.card_name': 'Cardholder Name',
            'client.settings.billing.payment.expiry': 'Expiration (MM/YY)',

            'pro.settings.notifications.title': 'Notification Routing',
            'pro.settings.notifications.messages.title': 'Chat Messages',
            'pro.settings.notifications.messages.desc': 'Receive alerts when clients send you direct messages.',
            'pro.settings.notifications.fatigue.title': 'High Fatigue Reports',
            'pro.settings.notifications.fatigue.desc': 'Alerts when a client reports RPE 8+ after a session.',
            'pro.settings.notifications.skipped.title': 'Skipped Exercises',
            'pro.settings.notifications.skipped.desc': 'Alerts when a client skips an exercise multiple times across sessions.',
            'pro.settings.notifications.missed.title': 'Missed Sessions',
            'pro.settings.notifications.missed.desc': 'Alerts when a client skips multiple training days consecutively.',
            'pro.settings.notifications.system.title': 'System Updates',
            'pro.settings.notifications.system.desc': 'Receive notifications when clients accept invites or complete billing.',

            'pro.settings.billing.bank.title': 'Bank Configuration',
            'pro.settings.billing.bank.desc': 'Link your bank account to receive payouts directly from client subscriptions.',
            'pro.settings.billing.bank.holder': 'Account Holder Name',
            'pro.settings.billing.bank.routing': 'Routing Number',
            'pro.settings.billing.bank.account': 'Account Number',

            'pro.settings.billing.plans.title': 'Subscription Plans',
            'pro.settings.billing.plans.desc': 'Create and manage the default billing tiers available for your clients.',
            'pro.settings.billing.plans.add': 'Add Plan',
            'pro.settings.billing.plans.level': 'Plan Level',
            'pro.settings.billing.plans.name': 'Plan Name',
            'pro.settings.billing.plans.price': 'Monthly Price ($)',

            'client.settings.placeholder.title': 'Configuration',
            'client.settings.placeholder.desc': 'This module is currently disabled in the prototype environment.',

            'settings.title': 'Settings',
            'settings.subtitle.pro': 'Manage your professional coaching profile and subscription.',
            'settings.subtitle.client': 'Update your personal details and app preferences.',
            'settings.tabs.profile': 'Profile & Brand',
            'settings.tabs.profile_client': 'Account Details',
            'settings.tabs.notifications': 'Notifications',
            'settings.tabs.preferences': 'App Preferences',
            'settings.tabs.billing': 'Billing & Plan',
            'settings.tabs.integrations': 'Integrations',
            'settings.tabs.coach': 'My Coach',

            'settings.btn.save': 'Save Changes',
            'settings.profile.title.pro': 'Professional Brand',
            'settings.profile.title.client': 'Personal Information',
            'settings.profile.photo.change': 'Change Photo',
            'settings.profile.photo.remove': 'Remove Photo',
            'settings.profile.form.first_name': 'First Name',
            'settings.profile.form.last_name': 'Last Name',
            'settings.profile.form.email': 'Email Address',
            'settings.profile.form.bio': 'Bio / Specialties',

            'preferences.title': 'App Preferences',
            'preferences.theme.title': 'Appearance (Theme)',
            'preferences.theme.desc': 'Toggle between Light and Dark mode globally.',
            'preferences.theme.light': 'Switch to Light',
            'preferences.theme.dark': 'Switch to Dark',
            'preferences.lang.title': 'Language',
            'preferences.lang.desc': 'Select your preferred display language.',
            'preferences.units.title': 'Measurement Units',
            'preferences.units.desc': 'Choose between Metric (kg/cm) and Imperial (lbs/in).',

            'reports.title': 'Reports & Exports',
            'reports.subtitle': 'Generate custom data exports for billing, adherence, and client history.',
            'reports.generator.title': 'Create New Report',
            'reports.form.type': 'Report Type',
            'reports.type.performance': 'Overall Roster Performance & Adherence',
            'reports.type.billing': 'Billing & Revenue Summary',
            'reports.type.history': 'Specific Client History (Workouts & Logs)',
            'reports.form.scope': 'Target Scope',
            'reports.scope.all': 'All Active Clients',
            'reports.scope.specific': 'Specific Client...',
            'reports.form.client': 'Select Client',
            'reports.form.client.placeholder': 'Choose a client...',
            'reports.form.range': 'Date Range',
            'reports.range.30days': 'Last 30 Days',
            'reports.range.lastmonth': 'Last Month',
            'reports.range.ytd': 'Year to Date (YTD)',
            'reports.range.custom': 'Custom Range...',
            'reports.form.start': 'Start Date',
            'reports.form.end': 'End Date',
            'reports.form.format': 'Export Format',
            'reports.format.pdf': 'PDF Document',
            'reports.format.csv': 'CSV / Excel',
            'reports.btn.generate': 'Generate Report',
            'reports.btn.generating': 'Generating...',
            'reports.help.wait': 'Please wait, preparing your document...',
            'reports.help.ready': 'Generation usually takes 1-2 seconds.',
            'reports.history.title': 'Recent Reports',
            'reports.history.view_all': 'View All',
            'reports.history.empty': 'No reports generated yet.',
            'reports.history.col.name': 'Report Name',
            'reports.history.col.type': 'Type',
            'reports.history.col.date': 'Generated',
            'reports.history.col.status': 'Status',
            'reports.history.col.actions': 'Actions',
            'reports.history.btn.download': 'Download',
            'reports.history.status.completed': 'Completed',
            'reports.warning.scope.title': 'Specific Scope Required:',
            'reports.warning.scope.desc': 'Client history reports can only be generated for a single specific client. Please change the Target Scope above.',

            'client.chat.title': 'Coach Alex',
            'client.chat.status.online': 'Online',
            'client.chat.input.placeholder': 'Message Coach...',
            'client.chat.input.editing': 'Editing message...',
            'client.chat.replying': 'Replying to ',
            'client.chat.you': 'You',
            'client.chat.coach': 'Coach',
            'client.chat.edited': '(edited)',
            'client.chat.menu.reply': 'Reply to Message',
            'client.chat.tag.general': 'General',
            'client.chat.tag.form_check': 'Form Check',
            'client.chat.tag.rpe_report': 'RPE Report',
            'client.chat.tag.question': 'Question',
            'client.chat.tag.checkin': 'Check-in',

            'reports.export.pdf.performance.title': 'ShapeUp - Performance Report',
            'reports.export.pdf.billing.title': 'Billing & Revenue Summary',
            'reports.export.pdf.history.title': 'Client History',
            'reports.export.pdf.generated': 'Generated on:',
            'reports.export.pdf.period': 'Period:',
            'reports.export.pdf.roster_status': 'Active Roster Status as of',
            'reports.export.pdf.no_history': 'No workout history found for this period.',
            'reports.export.pdf.not_implemented': 'This report type is not yet implemented for real data.',

            'reports.export.billing.col.name': 'Client Name',
            'reports.export.billing.col.status': 'Status',
            'reports.export.billing.col.type': 'Billing Type',
            'reports.export.billing.col.detail': 'Plan Detail',
            'reports.export.billing.col.rate': 'Monthly Rate ($)',

            'reports.export.perf.col.name': 'Client Name',
            'reports.export.perf.col.status': 'Status',
            'reports.export.perf.col.completed': 'Completed',
            'reports.export.perf.col.skipped': 'Skipped',
            'reports.export.perf.col.adherence': 'Adherence %',
            'reports.export.perf.col.volume': 'Total Volume (kg)',

            'reports.export.history.col.date': 'Date',
            'reports.export.history.col.plan': 'Plan Name',
            'reports.export.history.col.status': 'Status',
            'reports.export.history.col.ex': 'Exercise Name',
            'reports.export.history.col.logs': 'Set Details',
            'reports.export.history.col.rpe': 'Exercise RPE',
            'reports.export.history.col.comments': 'Session Comments',
            'reports.export.history.pdf.ex': 'Exercise',
            'reports.export.history.pdf.logs': 'Logs',
            'reports.export.history.pdf.rpe': 'Session RPE',

            'reports.export.summary.financial': 'Financial Summary',
            'reports.export.summary.clients': 'Total Clients in Scope:',
            'reports.export.summary.mrr': 'Total Monthly Recurring Revenue (MRR):',
            'reports.export.summary.perf': 'Summary Statistics',
            'reports.export.summary.perf.completed': 'Total Completed Sessions:',
            'reports.export.summary.perf.skipped': 'Total Skipped Sessions:',
            'reports.export.summary.perf.volume': 'Total Volume (Roster):',
            'reports.export.summary.perf.adherence': 'Average Roster Adherence:',

            'reports.export.val.skipped': 'Skipped',
            'reports.export.val.completed': 'Completed',
            'reports.export.val.done': 'Done',
            'reports.export.val.plan': 'Standard Plan',
            'reports.export.val.custom': 'Custom Agreement',
            'reports.export.val.active': 'Active',
            'reports.export.val.inactive': 'Inactive',

            'tour.clients.1': 'Welcome to the Clients screen! Here you manage active and inactive trainees.',
            'tour.clients.2': 'To add a new trainee, click here. They will receive an email invitation to join ShapeUp.',
            'tour.clients.3': 'Use this menu to quickly search by name or filter clients by status (Active, Inactive, Needs Attention).',
            'tour.clients.4': 'Click anywhere on the row to open the client\'s detailed profile.',
            'tour.clients.5': 'Here are quick shortcuts: temporarily suspend access (pause), manage billing, or delete the client.',
            'tour.clients.6': 'Your registered clients will appear here in this list view table.',
            'tour.clients.7': 'When you invite a new client, they appear here at the bottom of the list.',
            'tour.clients.8': 'Their initial status will be "Invited" until they create their account and accept.',
            'tour.clients.9': 'Click here to assign or modify the billing plan for this client.',
            'tour.invite.1': 'Enter the email address of your client here. They will receive an invitation to join.',
            'tour.invite.2': 'After filling the email, click here to send the invite.',
            'tour.billing.1': 'You can assign a standard subscription tier or set a custom fixed price for this client.',
            'tour.billing.2': 'After choosing the model, click here to apply the changes to their billing profile.',
            'tour.dashboard_pro.1': 'Welcome to the Professional Dashboard! Here you have full control of your trainees and manage their training plans.',
            'tour.dashboard_pro.2': 'Quickly track your business\'s core KPIs, such as active clients, attendance, and overall engagement.',
            'tour.dashboard_pro.3': 'In this feed, you keep a close eye on all your clients\' activities: completed workouts, skipped ones, and system notifications.',
            'tour.dashboard_pro.4': 'Your important invites and alerts will appear here, so nothing goes unnoticed.',
            'tour.training_pro.1': 'This is your Plan Library. Here you create and manage workout templates that can be assigned to any client.',
            'tour.training_pro.2': 'Use the Plan Builder to assemble a new training cycle from scratch.',
            'tour.training_pro.3': 'Here are your saved plans. You can edit them or quickly assign them directly to your clients.',
            'tour.settings_pro.1': 'This is your Professional Settings panel. Click on the tabs below to configure everything.',
            'tour.settings_pro.2': 'In "Profile & Brand", you can update your avatar, name, bio, and other contact info.',
            'tour.settings_pro.3': 'In "Notifications", choose which system alerts and emails you want to receive.',
            'tour.settings_pro.4': 'In "Billing & Plan", configure your bank account details and define the subscription tiers you offer to clients.',
            'tour.analytics.1': 'Welcome to Insights! This screen provides a strategic and financial overview of your business, updated in real-time based on your clients\' data.',
            'tour.analytics.2': 'The 4 main KPIs display: Monthly Recurring Revenue (MRR), Active Clients, Global Average Adherence, and Client Average Lifespan.',
            'tour.analytics.3': 'The charts display the growth of your client base over the last 6 months and the training adherence distribution. Use them to identify trends and improvement opportunities.',
            'tour.analytics.4': 'This is your Specialist Desk! Add exercises by clicking the button and then prescribe the sets by adjusting Type (Warm-up, Top set, etc.), Reps, Load, and RPE for each row.',
            'tour.analytics.5': 'Our Intelligence panel tracks your edits in real-time. It calculates the estimated workout duration, intensity distribution across sets, and provides a valuable summary!',
            'tour.clientdetail.1': 'This is your Specialist Desk! Add exercises by clicking the button and then prescribe the sets by adjusting Type (Warm-up, Top set, etc.), Reps, Load, and RPE for each row.',
            'tour.clientdetail.2': 'Our Intelligence panel tracks your edits in real-time. It calculates the estimated workout duration, intensity distribution across sets, and provides a valuable summary!',
            'tour.clientdetail.3': 'On this screen, you have a complete view of your client\'s profile. You can view the alert if there is a \'Needs Attention\' flag on their board.',
            'tour.clientdetail.4': 'Navigate between Analytics (Metrics and Evolution Charts) and Training Plans (Create and assign routines).',
            'tour.clientdetail.5': 'In the Analytics tab, this dashboard concentrates vital charts and indicators, such as Volume, Attendance, Weight History, and Personal Records (PRs) broken.',
            'tour.clientdetail.6': 'Since this client has not logged any workouts yet, the Analytics area is empty. The vital charts and panels will automatically appear here as soon as they complete their first session!',
            'tour.clientdetail.7': 'When your client logs their bodyweight, the progression chart will be generated here.',

            'tour.dashboard_client.1': 'Welcome to your Dashboard! Here you can check your upcoming workouts and recent performance.',
            'tour.dashboard_client.2': 'The Daily Check-in helps your coach understand how you feel before you even start exercising.',
            'tour.dashboard_client.3': 'Here you can quickly see your active training plan and jump straight into your next workout.',
            'tour.dashboard_client.4': 'Your recent completed activities and unlocked achievements will appear in this timeline.',

            'tour.training_client.1': 'This is your Training Hub. Here you can find all the plans and sessions assigned by your coach.',
            'tour.training_client.2': 'Click here to begin your session! The ShapeUp Engine will guide you through exercises, rest timers, and track your PRs.',
            'tour.training_client.3': 'This calendar shows your past workouts. You can click on any completed day to see your results.',

            'tour.session_engine.1': 'Your global session timer runs here. You can click Cancel at any point to stop without saving.',
            'tour.session_engine.2': 'Your automated rest timer lives here. It starts when you finish a set. You can manually adjust the rest time by adding or removing 15 seconds, or skip it entirely.',
            'tour.session_engine.3': 'Here are your exercises! Log your completed Reps and Weight for each set. Check the Failure box if you pushed to your absolute limit.',
            'tour.session_engine.4': 'Click "+ Set" at the bottom of any exercise to add an extra set, like a drop set or a warmup, if you need to do more than planned.',
            
            'tour.objectives.1': 'Welcome to Objectives! This is the place to track your body metrics and specific fitness goals over time.',
            'tour.objectives.2': 'Set your target weight here. This gives you a clear goal to work towards.',
            'tour.objectives.3': 'Log your bodyweight regularly. Your entries will automatically draw a trend line showing your progress.',

            'tour.settings.profile.info': 'You can change your name, contact info, and preferred language/units here.',
            'tour.settings.4': 'Choose between Light and Dark mode, or let the app follow your system settings. You can also change the language and units of measurement here.',
            'tour.settings.billing.payment': 'Manage your saved payment methods and view your billing history.',

            'tour.settings_client.1': 'Welcome to Settings! You can personalize your app experience here.',
            'tour.settings_client.2': 'Update your profile photo and personal details in this section.',
            'tour.settings_client.3': 'Check your active subscription tier and billing cycle here.',
            'tour.settings_client.4': 'Customize which alerts you want to receive, like workout reminders or new messages from your coach.'
        },
        'pt-BR': {
            'nav.dashboard': 'Painel',
            'nav.clients': 'Clientes',
            'nav.training_plans': 'Planos de Treino',
            'nav.my_training': 'Meus Treinos',
            'nav.exercises_library': 'Biblioteca de Exercícios',
            'nav.reports': 'Relatórios',
            'nav.feedback': 'E-mail / Dúvidas',
            'nav.analytics': 'Insights',
            'nav.settings': 'Configurações',
            'nav.objectives': 'Objetivos',
            'sidebar.chat': 'Falar com Treinador',

            'pro.dashboard.title': 'Visão Geral do Painel',
            'pro.dashboard.subtitle': 'Veja o que está acontecendo com seus clientes hoje.',
            'pro.dashboard.invite': 'Convidar Cliente',
            'pro.dashboard.metric.active': 'Clientes Ativos',
            'pro.dashboard.metric.active.sub': 'Portfólio Ativo Total',
            'pro.dashboard.metric.completed': 'Treinos Concluídos',
            'pro.dashboard.metric.completed.sub': 'Volume Global 30 dias',
            'pro.dashboard.metric.skipped': 'Treinos Pulados',
            'pro.dashboard.metric.skipped.sub': 'Precisa de Atenção',
            'pro.dashboard.metric.engagement': 'Engajamento Médio',
            'pro.dashboard.metric.engagement.sub': 'Adesão à Plataforma',

            'pro.dashboard.feed.title': 'Feed de Atividades Global',
            'pro.dashboard.search': 'Buscar...',
            'pro.dashboard.filter.all': 'Todas as Entradas',
            'pro.dashboard.filter.workout': 'Treinos',
            'pro.dashboard.filter.message': 'Mensagens',
            'pro.dashboard.filter.alert': 'Alertas',
            'pro.dashboard.filter.system': 'Sistema',
            'pro.dashboard.btn.clear': 'Limpar',
            'pro.dashboard.feed.empty': 'Nenhuma atividade encontrada com estes filtros.',
            'pro.dashboard.feed.page': 'Página',
            'pro.dashboard.feed.of': 'de',
            'pro.dashboard.alerts.title': 'Alertas de Clientes',
            'pro.dashboard.alerts.empty': 'Todos os clientes estão no caminho certo.',
            'sidebar.logout': 'Sair',
            'header.role.pro': 'Profissional',
            'header.role.client': 'Cliente',

            'clients.title': 'Gestão de Clientes',
            'clients.subtitle': 'Diretório dos seus alunos ativos e inativos.',
            'clients.invite': 'Convidar Novo Cliente',
            'clients.search': 'Buscar clientes...',
            'clients.filter': 'Filtrar',
            'clients.table.client': 'Cliente',
            'clients.table.plan': 'Plano Ativo',
            'clients.table.compliance': 'Adesão',
            'clients.table.checkin': 'Último Check-in',
            'clients.table.status': 'Status',
            'clients.table.actions': 'Ações',
            'clients.modal.delete.title': 'Excluir Cliente?',
            'clients.modal.delete.body': 'será permanentemente removido da sua lista. Esta ação não pode ser desfeita.',
            'clients.modal.delete.cancel': 'Cancelar',
            'clients.modal.delete.confirm': 'Excluir Cliente',
            'clients.modal.toggle.title.act': 'Reativar Cliente?',
            'clients.modal.toggle.body.act': '{{name}} será restaurado para o estado ativo e recuperará o acesso aos seus planos de treino.',
            'clients.modal.toggle.confirm.act': 'Reativar Cliente',
            'clients.modal.toggle.cancel': 'Cancelar',
            'clients.modal.toggle.title.inact': 'Suspender Cliente?',
            'clients.modal.toggle.body.inact': '{{name}} será suspenso. Seus dados serão mantidos, mas o acesso aos programas ativos será bloqueado.',
            'clients.modal.toggle.confirm.inact': 'Suspender Cliente',
            'clients.invite.title': 'Convidar Novo Cliente',
            'clients.invite.subtitle': 'Envie um e-mail de convite para seu cliente. Eles receberão um link para criar sua conta no ShapeUp e se conectar com você.',
            'clients.invite.label': 'E-mail do Cliente',
            'clients.invite.placeholder': 'cliente@exemplo.com',
            'clients.invite.btn.cancel': 'Cancelar',
            'clients.invite.btn.send': 'Enviar Convite',
            'clients.invite.error.empty': 'Por favor, insira um endereço de e-mail.',
            'clients.invite.error.invalid': 'Por favor, insira um endereço de e-mail válido.',
            'clients.invite.success.title': 'Convite Enviado!',
            'clients.invite.success.desc': 'Um convite foi enviado para {{email}}. Eles receberão um e-mail com um link para participar do seu programa de treinamento.',
            'clients.invite.success.btn': 'Concluído',

            'clients.billing.title': 'Atribuir Plano de Cobrança',
            'clients.billing.for': 'Configurando cobrança para:',
            'clients.billing.type.plan': 'Plano de Assinatura',
            'clients.billing.type.custom': 'Valor Fixo Customizado',
            'clients.billing.plan.label': 'Selecione um Plano',
            'clients.billing.plan.empty': 'Nenhum plano de assinatura disponível. Acesse Configurações > Faturamento e Plano para criar seus níveis (tiers).',
            'clients.billing.custom.label': 'Preço Mensal Fixo (R$ ou U$)',
            'clients.billing.custom.help': 'Isso substitui os planos regulares de assinatura e cobra deste cliente específico um valor mensal fixo selecionado por você.',
            'clients.billing.btn.cancel': 'Cancelar',
            'clients.billing.btn.apply': 'Aplicar Cobrança',

            'clients.status.active': 'Ativo',
            'clients.status.attention': 'Precisa de Atenção',
            'clients.status.invited': 'Convidado',
            'clients.status.inactive': 'Inativo',
            'pro.training.title.builder': 'Construtor de Planos',
            'pro.training.title.library': 'Biblioteca de Treinos',
            'pro.training.subtitle.builder': 'Crie modelos de treinos reutilizáveis e analise o volume.',
            'pro.training.subtitle.library': 'Gerencie seus modelos de treino e atribua aos clientes.',
            'pro.training.btn.create': 'Criar Novo Plano',
            'pro.training.btn.back': 'Voltar para Biblioteca',
            'pro.training.empty.title': 'Sua Biblioteca de Modelos está Vazia',
            'pro.training.empty.desc': 'Crie modelos de treino reutilizáveis para atribuí-los facilmente aos seus clientes.',
            'pro.training.empty.btn': 'Criar Primeiro Plano',
            'pro.training.card.exercises': 'Exercícios',
            'pro.training.card.sets': 'Séries',
            'pro.training.card.time': 'Tempo Est.',
            'pro.training.card.btn.edit': 'Editar Modelo',
            'pro.training.card.btn.assign': 'Atribuir a Cliente',
            'pro.training.assign.modal.title': 'Atribuir a Cliente',
            'pro.training.assign.modal.desc': 'Selecione um cliente para atribuir este modelo:',
            'pro.training.assign.empty': 'Nenhum cliente ativo encontrado.',
            'pro.training.assign.success.title': 'Modelo Atribuído',
            'pro.training.assign.success.message': 'O modelo foi atribuído com sucesso ao cliente.',
            'pro.training.assign.success.btn': 'Ótimo!',
            'pro.exercises.title': 'Biblioteca de Exercícios',
            'pro.exercises.subtitle': 'Navegue e gerencie o banco de dados global de exercícios.',
            'pro.exercises.btn.suggest': 'Sugerir Novo Exercício',
            'pro.exercises.search': 'Buscar exercícios por nome...',
            'pro.exercises.filter': 'Músculos',
            'pro.exercises.filter.header': 'Filtrar por Músculo Alvo',
            'pro.exercises.filter.clear': 'Limpar Filtros',
            'pro.exercises.empty': 'Nenhum exercício encontrado com esses critérios.',

            'pro.feedback.title': 'Feedback & Mensagens',
            'pro.feedback.subtitle': 'Revise check-ins, vídeos de execução e mensagens diretas.',
            'pro.feedback.search': 'Buscar mensagens...',
            'pro.feedback.empty.list': 'Nenhuma mensagem ainda.',
            'pro.feedback.ticket.action': 'Ação Necessária',
            'pro.feedback.ticket.needs': 'Atenção Necessária: ',
            'pro.feedback.ticket.general': 'Chat Geral',
            'pro.feedback.btn.resolve': 'Marcar como Resolvido',
            'pro.feedback.unread.new': 'Novas Mensagens Abaixo',
            'pro.feedback.replying': 'Respondendo a ',
            'pro.feedback.you': 'Você',
            'pro.feedback.attachment.doc': 'Anexo da Mensagem',
            'pro.feedback.input.placeholder': 'Responder para ',
            'pro.feedback.input.btn': 'Enviar Resposta',
            'pro.feedback.empty.thread.title': 'Nenhuma Mensagem Selecionada',
            'pro.feedback.empty.thread.desc': 'Selecione uma conversa do feed para visualizar os detalhes.',
            'pro.feedback.menu.reply': 'Responder Mensagem',

            'pro.analytics.title': 'Análises de Negócio',
            'pro.analytics.subtitle': 'Acompanhe o crescimento do seu negócio e o desempenho geral dos clientes.',
            'pro.analytics.btn.export': 'Exportar Relatório',
            'pro.analytics.metric.mrr': 'Receita Mensal Recorrente',
            'pro.analytics.metric.mrr.trend': 'Baseado nas Assinaturas Atuais',
            'pro.analytics.metric.clients': 'Clientes Ativos',
            'pro.analytics.metric.clients.trend': 'Listas em Tempo Real',
            'pro.analytics.metric.adherence': 'Adesão Global',
            'pro.analytics.metric.adherence.trend': 'Calculado sobre P. Ativos',
            'pro.analytics.metric.lifespan': 'Tempo Médio de Vida do Cliente',
            'pro.analytics.metric.lifespan.unit': ' meses',
            'pro.analytics.metric.lifespan.trend': 'Estável',
            'pro.analytics.chart.growth': 'Crescimento e Retenção de Clientes',
            'pro.analytics.chart.growth.active': 'Clientes Ativos',
            'pro.analytics.chart.growth.churned': 'Cancelados',
            'pro.analytics.chart.adherence': 'Distribuição de Adesão',
            'pro.analytics.chart.adherence.clients': 'Clientes',

            'pro.client.btn.message': 'Enviar Mensagem',
            'pro.client.tabs.analytics': 'Análise',
            'pro.client.tabs.plans': 'Planos de Treino',
            'pro.client.empty.analytics.title': 'Sem Dados Disponíveis',
            'pro.client.empty.analytics.desc': 'Este cliente ainda não registrou nenhum treino. As análises aparecerão quando ele completar uma sessão.',
            'pro.client.chart.volume': 'Tendência de Volume',
            'pro.client.chart.rpe': 'Tendência de RPE (Esforço)',
            'pro.client.chart.weight': 'Tendência de Peso',
            'pro.client.chart.weight.empty': 'O cliente precisa registrar pelo menos 2 pesos na aba Objetivos para gerar esta tendência.',
            'pro.client.chart.adherence': 'Adesão (Últimos 30 Dias)',
            'pro.client.adherence.completed': 'Concluído',
            'pro.client.adherence.skipped': 'Pulado',
            'pro.client.adherence.partial': 'Parcial',
            'pro.client.chart.prs': 'Recordes Pessoais Recentes',
            'pro.client.prs.empty': 'Nenhum recorde quebrado ainda.',
            'pro.client.prs.modal.title': 'PR:',
            'pro.client.prs.modal.desc': 'Comparando recorde anterior vs novo recorde',
            'pro.client.prs.modal.prev': 'Recorde Anterior',
            'pro.client.prs.modal.new': 'Novo Recorde',
            'pro.client.prs.modal.tag': 'NOVO PR',
            'pro.client.plan.active': 'Ativo',
            'pro.client.plan.weeks': 'semanas',
            'pro.client.plan.exercises': 'exercícios',
            'pro.client.plan.btn.edit': 'Editar',
            'pro.client.plan.btn.copy': 'Copiar',
            'pro.client.plan.empty.ex': 'Nenhum exercício ainda — clique em Editar para adicionar',
            'pro.client.plan.history.hide': 'Ocultar histórico',
            'pro.client.plan.history.show': 'Mostrar histórico',
            'pro.client.plan.history.tag.partial': 'Parcial',
            'pro.client.plan.history.tag.skipped.sess': 'Sessão Pulada',
            'pro.client.plan.history.tag.skipped.ex': 'Exercício Pulado',
            'pro.client.plan.delete.title': 'Excluir Plano?',
            'pro.client.plan.delete.desc': 'será permanentemente removido. Esta ação não pode ser desfeita.',
            'pro.client.plan.delete.cancel': 'Cancelar',
            'pro.client.plan.delete.confirm': 'Excluir Plano',
            'pro.client.plans.title': 'Planos Atribuídos',
            'pro.client.plans.btn.add': 'Adicionar Plano',
            'pro.client.plans.empty': 'Nenhum plano atribuído. Clique em "Adicionar Plano" para criar um.',

            'pro.builder.name': 'Nome do Plano',
            'pro.builder.weeks': 'Duração (Semanas)',
            'pro.builder.phase': 'Fase / Objetivo',
            'pro.builder.diff': 'Dificuldade',
            'pro.builder.notes': 'Notas Gerais',
            'pro.builder.notes.ph': 'ex: Foco em sobrecarga progressiva ao longo de 6 semanas...',
            'pro.builder.stack': 'Pilha de Exercícios',
            'pro.builder.add.ex': 'Adicionar Exercício',
            'pro.builder.ex.name.ph': 'Nome do exercício',
            'pro.builder.ex.tags.ph': 'Tags ex: Peito • Composto',
            'pro.builder.ex.notes.ph': 'Notas de execução...',
            'pro.builder.set.type': 'Tipo',
            'pro.builder.set.tech': 'Técnica',
            'pro.builder.set.reps': 'Reps',
            'pro.builder.set.load': 'Carga %',
            'pro.builder.set.rpe': 'RPE',
            'pro.builder.set.rest': 'Descanso (s)',
            'pro.builder.add.set': 'Adicionar Série',
            'pro.builder.error.title': 'Exercício Duplicado',
            'pro.builder.error.duplicate': 'Este exercício já está no plano.',
            'pro.builder.error.btn': 'Entendido',
            'pro.builder.summary.title': 'Resumo do Plano',
            'pro.builder.summary.ex': 'Total de Exercícios',
            'pro.builder.summary.sets': 'Total de Séries',
            'pro.builder.summary.sets.val': 'séries',
            'pro.builder.summary.time': 'Tempo Est.',
            'pro.builder.summary.rpe': 'RPE Médio Alvo',
            'pro.builder.summary.phase': 'Fase',
            'pro.builder.summary.diff': 'Dificuldade',
            'pro.builder.chart.intensity': 'Distribuição de Intensidade',
            'pro.builder.chart.tech': 'Uso de Técnica',
            'pro.builder.btn.save': 'Salvar Plano',
            'pro.builder.btn.assign': 'Atribuir ao Cliente',
            'pro.builder.btn.cancel': 'Cancelar',

            'client.dashboard.welcome': 'Bem-vindo de volta,',
            'client.dashboard.subtitle.nodata': 'Vá para Meus Treinos para começar sua primeira sessão!',
            'client.dashboard.metric.weekly': 'Volume Semanal',
            'client.dashboard.metric.streak': 'Dias Consecutivos',
            'client.dashboard.metric.sessions': 'Sessões Concluídas',
            'client.dashboard.trend.weekly.nosessions': 'Nenhuma sessão ainda',
            'client.dashboard.trend.weekly.first': 'Primeira semana!',
            'client.dashboard.trend.streak.start': 'Comece seu ritmo!',
            'client.dashboard.trend.streak.great': '🔥 Ótima consistência!',
            'client.dashboard.trend.streak.keep': 'Continue assim!',
            'client.dashboard.trend.sessions.noplans': 'Nenhum plano atribuído',
            'client.dashboard.trend.sessions.plans': 'Planos de treino',
            'client.dashboard.chart.title': 'Progressão de Volume',
            'client.dashboard.chart.nodata': 'Complete pelo menos 2 sessões para ver sua tendência.',
            'client.dashboard.achievements.title': 'Evoluções Recentes',
            'client.dashboard.achievements.nodata': 'Continue treinando e suas evoluções aparecerão aqui!',

            'client.training.title': 'Seus Planos de Treino',
            'client.training.empty.title': 'Nenhum Plano Atribuído',
            'client.training.empty.desc': 'Você não tem nenhum plano de treino atribuído a você ainda.',
            'client.training.card.difficulty': 'Dificuldade',
            'client.training.card.weeks': 'semanas',
            'client.training.card.exercises': 'Exercícios',
            'client.training.card.btn': 'Iniciar Sessão',
            'client.training.history.title': 'Histórico de Sessões',
            'client.training.history.empty': 'Nenhuma sessão de treino concluída ainda. Inicie um treino para construir seu histórico!',
            'client.training.history.vol': 'vol',
            'client.analysis.chart.vol': 'Vol Total (kg)',
            'client.analysis.chart.rpe': 'RPE (Dificuldade)',
            'client.training.pagination.prev': 'Anterior',
            'client.training.pagination.page': 'Página',
            'client.training.pagination.of': 'de',
            'client.training.pagination.next': 'Próximo',

            'client.session.btn.cancel': 'Cancelar Sessão',
            'client.session.resting': 'Descansando',
            'client.session.btn.skip': 'Pular',
            'client.session.modal.cancel.title': 'Cancelar Treino?',
            'client.session.modal.cancel.desc': 'Tem certeza que deseja cancelar esta sessão? Todo o progresso não salvo será perdido.',
            'client.session.modal.cancel.keep': 'Continuar Treinando',
            'client.session.modal.cancel.confirm': 'Cancelar Sessão',
            'client.session.modal.feedback.title': 'Como você se sente hoje?',
            'client.session.modal.feedback.desc': 'Avalie a dificuldade geral da sua sessão (RPE).',
            'client.session.modal.feedback.comments': 'Comentários para o Treinador',
            'client.session.modal.feedback.placeholder': 'Alguma dor? Se sentiu bem? Deixe uma nota...',
            'client.session.modal.feedback.submit': 'Enviar Avaliação',
            'client.session.modal.gamified.title': 'Treino Concluído!',
            'client.session.modal.gamified.desc': 'Excelente trabalho finalizando',
            'client.session.modal.gamified.fallback': 'seu treino',
            'client.session.modal.gamified.vol': 'Vol Total (kg)',
            'client.session.modal.gamified.duration': 'Duração',
            'client.session.modal.gamified.prs': 'Novos PRs',
            'client.session.modal.gamified.return': 'Voltar ao Painel',
            'client.session.card.details': 'Ver Detalhes',
            'client.session.table.set': 'Série',
            'client.session.table.target': 'Alvo',
            'client.session.table.rest': 'Desc.',
            'client.session.table.weight': 'Carga',
            'client.session.table.reps': 'Reps',
            'client.session.table.rpe': 'RPE',
            'client.session.table.failure': 'Falha',
            'client.session.table.done': 'Feito',
            'client.session.set_type.warmup': 'Aquecimento',
            'client.session.set_type.feeder': 'Preparação',
            'client.session.set_type.working': 'Trabalho',
            'client.session.set_type.topset': 'Top Set',
            'client.session.set_type.dropset': 'Drop Set',
            'client.session.set_type.backoff': 'Backoff',
            'client.session.btn.add_set': 'Adicionar Série',
            'client.session.btn.finish': 'Finalizar e Salvar',

            'client.exercise_modal.video': 'Vídeo Oficial de Execução',
            'client.exercise_modal.muscles': 'Músculos Alvo',
            'client.exercise_modal.notes.title': 'Notas de Execução',
            'client.exercise_modal.notes.desc.1': 'Esta é uma descrição padrão. Para executar o ',
            'client.exercise_modal.notes.desc.2': ', certifique-se de que sua forma seja consistente e que você controle a porção excêntrica do movimento. Mantenha o equipamento (',
            'client.exercise_modal.notes.desc.3': ') estável em toda a amplitude do movimento.',
            'client.exercise_modal.notes.bullet1': 'Mantenha a estabilidade do core.',
            'client.exercise_modal.notes.bullet2': 'Siga uma cadência 2-1-1-0 como base.',
            'client.exercise_modal.notes.bullet3': 'Expire na fase concêntrica.',

            'client.objectives.title': 'Seus Objetivos',
            'client.objectives.target.title': 'Meta Alvo',
            'client.objectives.target.label': 'Peso Meta (kg)',
            'client.objectives.target.btn': 'Atualizar Meta',
            'client.objectives.target.saved': 'Meta Salva!',
            'client.objectives.log.title': 'Registrar Peso de Hoje',
            'client.objectives.log.label': 'Peso de Hoje (kg)',
            'client.objectives.log.btn': 'Registrar Peso',
            'client.objectives.history.title': 'Histórico',
            'client.objectives.history.empty': 'Nenhum peso registrado ainda.',
            'client.objectives.chart.title': 'Tendência de Peso Corporal',
            'client.objectives.chart.empty': 'Registre pelo menos 2 pesos para ver seu gráfico de tendência.',
            'client.objectives.chart.series.weight': 'Peso (kg)',
            'client.objectives.chart.series.goal': 'Peso Meta',

            'client.settings.notifications.title': 'Preferências de Notificações',
            'client.settings.notifications.chat.title': 'Mensagens de Chat',
            'client.settings.notifications.chat.desc': 'Receba alertas quando seu treinador enviar uma mensagem direta.',
            'client.settings.notifications.plan.title': 'Atualizações do Plano',
            'client.settings.notifications.plan.desc': 'Notificações push quando seu plano de treino for modificado.',
            'client.settings.notifications.system.title': 'Lembretes do Sistema',
            'client.settings.notifications.system.desc': 'Atualizações da plataforma, status de conexão e check-ins automáticos.',

            'client.settings.billing.active.title': 'Assinatura Ativa',
            'client.settings.billing.active.empty.title': 'Nenhum Plano Atribuído',
            'client.settings.billing.active.empty.desc': 'Seu treinador ainda não atribuiu um plano de cobrança à sua conta.',
            'client.settings.billing.payment.title': 'Forma de Pagamento',
            'client.settings.billing.payment.desc': 'Salve os dados do seu cartão com segurança para cobrança mensal automática.',
            'client.settings.billing.payment.card_num': 'Número do Cartão',
            'client.settings.billing.payment.card_name': 'Nome no Cartão',
            'client.settings.billing.payment.expiry': 'Vencimento (MM/AA)',

            'pro.settings.notifications.title': 'Roteamento de Notificações',
            'pro.settings.notifications.messages.title': 'Mensagens de Chat',
            'pro.settings.notifications.messages.desc': 'Receba alertas quando os clientes enviarem mensagens diretas.',
            'pro.settings.notifications.fatigue.title': 'Relatórios de Alta Fadiga',
            'pro.settings.notifications.fatigue.desc': 'Alertas quando um cliente relata RPE 8+ após uma sessão.',
            'pro.settings.notifications.skipped.title': 'Exercícios Pulados',
            'pro.settings.notifications.skipped.desc': 'Alertas quando um cliente pula um exercício várias vezes.',
            'pro.settings.notifications.missed.title': 'Sessões Perdidas',
            'pro.settings.notifications.missed.desc': 'Alertas quando um cliente pula vários dias de treino consecutivos.',
            'pro.settings.notifications.system.title': 'Atualizações do Sistema',
            'pro.settings.notifications.system.desc': 'Receba notificações de convites aceitos ou atualizações de faturamento.',

            'pro.settings.billing.bank.title': 'Configuração Bancária',
            'pro.settings.billing.bank.desc': 'Vincule sua conta bancária para receber repasses das assinaturas dos clientes.',
            'pro.settings.billing.bank.holder': 'Nome do Titular da Conta',
            'pro.settings.billing.bank.routing': 'Número de Roteamento',
            'pro.settings.billing.bank.account': 'Número da Conta',

            'pro.settings.billing.plans.title': 'Planos de Assinatura',
            'pro.settings.billing.plans.desc': 'Crie e gerencie os níveis de cobrança padrão disponíveis para os seus clientes.',
            'pro.settings.billing.plans.add': 'Adicionar Plano',
            'pro.settings.billing.plans.level': 'Nível do Plano',
            'pro.settings.billing.plans.name': 'Nome do Plano',
            'pro.settings.billing.plans.price': 'Preço Mensal (R$)',

            'client.settings.placeholder.title': 'Configuração de',
            'client.settings.placeholder.desc': 'Este módulo está atualmente desabilitado no ambiente de protótipo.',

            'settings.title': 'Configurações',
            'settings.subtitle.pro': 'Gerencie seu perfil profissional e assinatura.',
            'settings.subtitle.client': 'Atualize seus detalhes pessoais e preferências do app.',
            'settings.tabs.profile': 'Perfil e Marca',
            'settings.tabs.profile_client': 'Detalhes da Conta',
            'settings.tabs.notifications': 'Notificações',
            'settings.tabs.preferences': 'Preferências do App',
            'settings.tabs.billing': 'Faturamento e Plano',
            'settings.tabs.integrations': 'Integrações',
            'settings.tabs.coach': 'Meu Treinador',

            'settings.btn.save': 'Salvar Alterações',
            'settings.profile.title.pro': 'Marca Profissional',
            'settings.profile.title.client': 'Informações Pessoais',
            'settings.profile.photo.change': 'Alterar Foto',
            'settings.profile.photo.remove': 'Remover Foto',
            'settings.profile.form.first_name': 'Nome',
            'settings.profile.form.last_name': 'Sobrenome',
            'settings.profile.form.email': 'Endereço de Email',
            'settings.profile.form.bio': 'Bio / Especialidades',

            'preferences.title': 'Preferências do App',
            'preferences.theme.title': 'Aparência (Tema)',
            'preferences.theme.desc': 'Alterne entre o modo Claro e Escuro globalmente.',
            'preferences.theme.light': 'Mudar para Claro',
            'preferences.theme.dark': 'Mudar para Escuro',
            'preferences.lang.title': 'Idioma',
            'preferences.lang.desc': 'Selecione o idioma de exibição de sua preferência.',
            'preferences.units.title': 'Unidades de Medida',
            'preferences.units.desc': 'Escolha entre Métrico (kg/cm) e Imperial (lbs/in).',

            'reports.title': 'Relatórios & Exportações',
            'reports.subtitle': 'Gere exportações de dados personalizadas para faturamento, adesão e histórico do cliente.',
            'reports.generator.title': 'Criar Novo Relatório',
            'reports.form.type': 'Tipo de Relatório',
            'reports.type.performance': 'Desempenho Geral e Adesão do Elenco',
            'reports.type.billing': 'Resumo de Faturamento e Receita',
            'reports.type.history': 'Histórico Específico do Cliente (Treinos e Logs)',
            'reports.form.scope': 'Escopo Alvo',
            'reports.scope.all': 'Todos os Clientes Ativos',
            'reports.scope.specific': 'Cliente Específico...',
            'reports.form.client': 'Selecionar Cliente',
            'reports.form.client.placeholder': 'Escolha um cliente...',
            'reports.form.range': 'Intervalo de Datas',
            'reports.range.30days': 'Últimos 30 Dias',
            'reports.range.lastmonth': 'Mês Passado',
            'reports.range.ytd': 'Ano até a Data (YTD)',
            'reports.range.custom': 'Intervalo Personalizado...',
            'reports.form.start': 'Data de Início',
            'reports.form.end': 'Data de Término',
            'reports.form.format': 'Formato de Exportação',
            'reports.format.pdf': 'Documento PDF',
            'reports.format.csv': 'CSV / Excel',
            'reports.btn.generate': 'Gerar Relatório',
            'reports.btn.generating': 'Gerando...',
            'reports.help.wait': 'Por favor aguarde, preparando seu documento...',
            'reports.help.ready': 'A geração leva geralmente 1-2 segundos.',
            'reports.history.title': 'Relatórios Recentes',
            'reports.history.view_all': 'Ver Tudo',
            'reports.history.empty': 'Nenhum relatório gerado ainda.',
            'reports.history.col.name': 'Nome do Relatório',
            'reports.history.col.type': 'Tipo',
            'reports.history.col.date': 'Gerado em',
            'reports.history.col.status': 'Status',
            'reports.history.col.actions': 'Ações',
            'reports.history.btn.download': 'Baixar',
            'reports.history.status.completed': 'Concluído',
            'reports.warning.scope.title': 'Escopo Específico Necessário:',
            'reports.warning.scope.desc': 'Relatórios de histórico do cliente só podem ser gerados para um único cliente específico. Por favor, altere o Escopo Alvo acima.',

            'client.chat.title': 'Treinador Alex',
            'client.chat.status.online': 'Online',
            'client.chat.input.placeholder': 'Falar com Treinador...',
            'client.chat.input.editing': 'Editando mensagem...',
            'client.chat.replying': 'Respondendo a ',
            'client.chat.you': 'Você',
            'client.chat.coach': 'Treinador',
            'client.chat.edited': '(editado)',
            'client.chat.menu.reply': 'Responder Mensagem',
            'client.chat.tag.general': 'Geral',
            'client.chat.tag.form_check': 'Análise de Técnica',
            'client.chat.tag.rpe_report': 'Relato de Esforço',
            'client.chat.tag.question': 'Dúvida',
            'client.chat.tag.checkin': 'Check-in',

            'reports.export.pdf.performance.title': 'ShapeUp - Relatório de Desempenho',
            'reports.export.pdf.billing.title': 'Resumo de Faturamento e Receita',
            'reports.export.pdf.history.title': 'Histórico Inicial do Cliente do Cliente',
            'reports.export.pdf.generated': 'Gerado em:',
            'reports.export.pdf.period': 'Período:',
            'reports.export.pdf.roster_status': 'Status da Lista Ativa em',
            'reports.export.pdf.no_history': 'Nenhum histórico encontrado para este período.',
            'reports.export.pdf.not_implemented': 'Este tipo de relatório não está implementado para dados reais.',

            'reports.export.billing.col.name': 'Cliente',
            'reports.export.billing.col.status': 'Status',
            'reports.export.billing.col.type': 'Tipo de Faturamento',
            'reports.export.billing.col.detail': 'Plano',
            'reports.export.billing.col.rate': 'Valor Mensal (R$)',

            'reports.export.perf.col.name': 'Cliente',
            'reports.export.perf.col.status': 'Status',
            'reports.export.perf.col.completed': 'Concluído',
            'reports.export.perf.col.skipped': 'Pulado',
            'reports.export.perf.col.adherence': 'Adesão %',
            'reports.export.perf.col.volume': 'Volume Total (kg)',

            'reports.export.history.col.date': 'Data',
            'reports.export.history.col.plan': 'Nome do Plano',
            'reports.export.history.col.status': 'Status',
            'reports.export.history.col.ex': 'Exercício',
            'reports.export.history.col.logs': 'Séries e Cargas',
            'reports.export.history.col.rpe': 'RPE do Ex',
            'reports.export.history.col.comments': 'Comentários',
            'reports.export.history.pdf.ex': 'Exercício',
            'reports.export.history.pdf.logs': 'Séries',
            'reports.export.history.pdf.rpe': 'RPE da Sessão',

            'reports.export.summary.financial': 'Resumo Financeiro',
            'reports.export.summary.clients': 'Total de Clientes Selecionados:',
            'reports.export.summary.mrr': 'Receita Recorrente Mensal (MRR):',
            'reports.export.summary.perf': 'Estatísticas Gerais',
            'reports.export.summary.perf.completed': 'Total de Sessões Concluídas:',
            'reports.export.summary.perf.skipped': 'Total de Sessões Puladas:',
            'reports.export.summary.perf.volume': 'Volume Total (Geral):',
            'reports.export.summary.perf.adherence': 'Adesão Média da Lista:',

            'reports.export.val.skipped': 'Pulado',
            'reports.export.val.completed': 'Concluído',
            'reports.export.val.done': 'Feito',
            'reports.export.val.plan': 'Plano Padrão',
            'reports.export.val.custom': 'Acordo Customizado',
            'reports.export.val.active': 'Ativo',
            'reports.export.val.inactive': 'Inativo',

            'tour.clients.1': 'Bem-vindo à tela de Clientes! Aqui você gerencia alunos ativos e inativos.',
            'tour.clients.2': 'Para inserir um novo aluno, clique aqui. Ele vai receber um e-mail de convite para participar do ShapeUp.',
            'tour.clients.3': 'Use este menu para rapidamente buscar por nome ou filtrar clientes por status (Ativo, Inativo, Precisa de Atenção).',
            'tour.clients.4': 'Clique em qualquer lugar da linha para abrir o perfil detalhado do cliente.',
            'tour.clients.5': 'Aqui estão atalhos rápidos: suspender acesso temporariamente (pausar), gerenciar faturamento, ou excluir o cliente.',
            'tour.clients.6': 'Seus clientes cadastrados aparecerão aqui nesta tabela em formato de lista.',
            'tour.clients.7': 'Quando você convida um novo cliente, ele aparece aqui no final da lista.',
            'tour.clients.8': 'O status inicial dele será "Convidado" até que ele crie a conta e aceite.',
            'tour.clients.9': 'Clique aqui para atribuir ou modificar o plano de cobrança deste cliente.',
            'tour.invite.1': 'Insira o endereço de e-mail do seu cliente aqui. Ele receberá o convite para criar uma conta ou se associar.',
            'tour.invite.2': 'Após preencher o e-mail, clique aqui para enviar o convite.',
            'tour.billing.1': 'Você pode atribuir um plano de assinatura padrão ou definir um preço fixo customizado para este cliente.',
            'tour.billing.2': 'Após escolher o modelo de cobrança, clique aqui para registrar no perfil dele.',
            'tour.dashboard_pro.1': 'Bem-vindo ao Painel do Profissional! Aqui você tem o controle total dos seus alunos e gerencia seus planos de treino.',
            'tour.dashboard_pro.2': 'Acompanhe rapidamente os KPIs vitais do seu negócio, como clientes ativos, adesão e engajamento geral.',
            'tour.dashboard_pro.3': 'Neste feed, você acompanha de perto todas as atividades dos clientes: treinos concluídos, ignorados e notificações do sistema.',
            'tour.dashboard_pro.4': 'Seus convites e alertas importantes aparecerão aqui, para que nada passe despercebido.',
            'tour.training_pro.1': 'Esta é a sua Biblioteca de Planos. Aqui você cria e gerencia os templates de treino que poderão ser atribuídos para qualquer cliente.',
            'tour.training_pro.2': 'Use o Construtor de Planos para montar um novo ciclo de treinamento a partir do zero.',
            'tour.training_pro.3': 'Aqui ficam seus planos salvos. Você pode editá-los ou atribuí-los rapidamente direto para seus clientes.',
            'tour.settings_pro.1': 'Este é o seu painel de Configurações Profissionais. Clique nas abas abaixo para configurar o sistema.',
            'tour.settings_pro.2': 'Em "Perfil e Marca", você atualiza sua foto, nome, biografia e outras informações de contato.',
            'tour.settings_pro.3': 'Em "Notificações", escolha quais alertas e e-mails do sistema você deseja receber.',
            'tour.settings_pro.4': 'Em "Faturamento e Plano", configure os dados da sua conta bancária e defina os planos de assinatura que você oferece aos clientes.',
            'tour.analytics.1': 'Bem-vindo ao Insights! Esta tela oferece uma visão estratégica e financeira do seu negócio, atualizada em tempo real com os dados dos seus clientes.',
            'tour.analytics.2': 'Os 4 KPIs principais mostram: Receita Recorrente Mensal (MRR), Clientes Ativos, Adesão Média Global e Tempo Médio de Vida do Cliente.',
            'tour.analytics.3': 'Os gráficos exibem o crescimento da sua base nos últimos 6 meses e a distribuição da adesão aos treinos. Use-os para identificar tendências e oportunidades de melhoria.',
            'tour.analytics.4': 'Esta é sua Mesa de Especialista! Adicione exercícios clicando no botão e, na sequência, prescreva as séries ajustando Tipo (Aquecimento, Série principal, etc.), Reps, Carga e RPE para cada linha.',
            'tour.analytics.5': 'Nosso painel de Inteligência acompanha suas edições em tempo real. Ele calcula o tempo estimado de treino, a distribuição de intensidade das séries e exibe um resumo valioso!',
            'tour.clientdetail.1': 'Esta é sua Mesa de Especialista! Adicione exercícios clicando no botão e, na sequência, prescreva as séries ajustando Tipo (Aquecimento, Série principal, etc.), Reps, Carga e RPE para cada linha.',
            'tour.clientdetail.2': 'Nosso painel de Inteligência acompanha suas edições em tempo real. Ele calcula o tempo estimado de treino, a distribuição de intensidade das séries e exibe um resumo valioso!',
            'tour.clientdetail.3': 'Nesta tela você tem a visão completa do perfil do seu cliente. Você pode visualizar o alerta caso exista um foco de "Atenção" no quadro dele.',
            'tour.clientdetail.4': 'Navegue entre o Analytics (Métricas e Gráficos de Evolução) e o Planos de Treino (Criação e prescrição de rotinas).',
            'tour.clientdetail.5': 'Na aba Analytics, este painel concentra gráficos e indicadores vitais, como Volume, Assiduidade, Histórico de Peso e Quebra de Recordes Pessoais (PRs).',
            'tour.clientdetail.6': 'Como este aluno ainda não realizou nenhum treino, a área de Analytics está vazia. Os gráficos e painéis vitais aparecerão aqui automaticamente assim que ele completar sua primeira sessão!',
            'tour.clientdetail.7': 'Quando seu cliente registrar o peso corporal, o gráfico de progressão será gerado aqui.',

            'tour.dashboard_client.1': 'Bem-vindo ao seu Painel! Aqui você pode conferir seus próximos treinos e seu desempenho recente.',
            'tour.dashboard_client.2': 'O Check-in Diário ajuda seu treinador a entender como você se sente antes mesmo de começar a se exercitar.',
            'tour.dashboard_client.3': 'Aqui você pode ver rapidamente seu plano de treino ativo e pular direto para sua próxima sessão.',
            'tour.dashboard_client.4': 'Suas atividades recentes concluídas e conquistas desbloqueadas aparecerão nesta linha do tempo.',

            'tour.training_client.1': 'Bem-vindo! Aqui você encontra todos os planos e sessões atribuídos pelo seu treinador.',
            'tour.training_client.2': 'Clique aqui para começar o treino! O sistema guiará você pelos exercícios, intervalos e registrará seus recordes.',
            'tour.training_client.3': 'Este calendário mostra seus treinos passados. Clique em qualquer dia concluído para ver seus resultados.',

            'tour.session_engine.1': 'O cronômetro global do treino roda aqui. Você pode Cancelar a qualquer momento se precisar parar sem salvar.',
            'tour.session_engine.2': 'Seu cronômetro de descanso automático fica aqui. Ele começa quando você termina uma série. Você pode ajustar adicionando ou removendo 15s, ou até pular o descanso inteiro.',
            'tour.session_engine.3': 'Aqui estão seus exercícios! Registre suas repetições feitas e a carga de cada série. Marque a caixa de "Falha" se você foi até o seu limite absoluto.',
            'tour.session_engine.4': 'Clique em "+ Série" no final de qualquer exercício para adicionar uma série extra, como um drop set ou aquecimento.',
            
            'tour.objectives.1': 'Bem-vindo aos Objetivos! Este é o lugar para rastrear suas métricas corporais e metas de condicionamento ao longo do tempo.',
            'tour.objectives.2': 'Defina seu peso alvo aqui. Isso te dá uma meta clara para focar.',
            'tour.objectives.3': 'Registre seu peso regularmente. Suas entradas desenharão automaticamente uma linha de tendência mostrando seu progresso.',

            'tour.settings.profile.info': 'Altere seu nome, contato e preferências de idioma e unidades de medida por aqui.',
            'tour.settings.4': 'Escolha entre o Modo Claro ou Escuro, ou deixe o app seguir a configuração do seu sistema. Aqui também pode escolher o idioma e unidades de medida.',
            'tour.settings.billing.payment': 'Gerencie seus métodos de pagamento salvos e visualize seu histórico de cobranças.',

            'tour.settings_client.1': 'Bem-vindo às Configurações! Você pode personalizar sua experiência no aplicativo por aqui.',
            'tour.settings_client.2': 'Atualize sua foto de perfil e dados pessoais nesta seção.',
            'tour.settings_client.3': 'Verifique seu nível de assinatura ativo e o ciclo de cobrança aqui.',
            'tour.settings_client.4': 'Personalize quais alertas deseja receber, como lembretes de treino ou novas mensagens do seu treinador.'
        }
    };

    const t = (key) => {
        return translations[language]?.[key] || translations['en'][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t, unitSystem, setUnitSystem, convertWeight, formatWeight }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
