import React, { createContext, useState, useEffect, useContext } from 'react';

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [language, setLanguageState] = useState('en');

    useEffect(() => {
        // Auto detect language on first load if not set
        const storedLang = localStorage.getItem('shapeup_language');
        if (storedLang) {
            setLanguageState(storedLang);
        } else {
            const browserLang = navigator.language || navigator.userLanguage;
            const defaultLang = browserLang.toLowerCase().includes('pt') ? 'pt-BR' : 'en';
            setLanguageState(defaultLang);
            localStorage.setItem('shapeup_language', defaultLang);
        }
    }, []);

    const setLanguage = (lang) => {
        setLanguageState(lang);
        localStorage.setItem('shapeup_language', lang);
    };

    // Dictionary for the Settings page and Sidebar
    const translations = {
        'en': {
            'nav.dashboard': 'Dashboard',
            'nav.clients': 'Clients',
            'nav.training_plans': 'Training Plans',
            'nav.my_training': 'My Training',
            'nav.exercises_library': 'Exercises Library',
            'nav.reports': 'Reports',
            'nav.feedback': 'Feedback',
            'nav.analytics': 'Analytics',
            'nav.settings': 'Settings',
            'nav.objectives': 'Objectives',
            'sidebar.chat': 'Chat with Coach',

            'pro.dashboard.title': 'Dashboard Overview',
            'pro.dashboard.subtitle': "Here's what's happening with your clients today.",
            'pro.dashboard.invite': 'Invite Client',
            'pro.dashboard.metric.active': 'Active Clients',
            'pro.dashboard.metric.active.sub': 'Total Active Portfolio',
            'pro.dashboard.metric.completed': 'Workouts Completed',
            'pro.dashboard.metric.completed.sub': 'Global 30-day Volume',
            'pro.dashboard.metric.skipped': 'Workouts Skipped',
            'pro.dashboard.metric.skipped.sub': 'Needs Attention',
            'pro.dashboard.metric.engagement': 'Avg. Engagement',
            'pro.dashboard.metric.engagement.sub': 'Platform Compliance',

            'pro.dashboard.feed.title': 'Global Client Activity Feed',
            'pro.dashboard.search': 'Search...',
            'pro.dashboard.filter.all': 'All Entries',
            'pro.dashboard.filter.workout': 'Workouts',
            'pro.dashboard.filter.message': 'Messages',
            'pro.dashboard.filter.alert': 'Alerts',
            'pro.dashboard.filter.system': 'System',
            'pro.dashboard.btn.clear': 'Clear',
            'pro.dashboard.feed.empty': 'No client activity found for these filters.',
            'pro.dashboard.feed.page': 'Page',
            'pro.dashboard.feed.of': 'of',
            'pro.dashboard.alerts.title': 'Client Alerts',
            'pro.dashboard.alerts.empty': 'All clients are currently on track.',
            'sidebar.logout': 'Log out',
            'header.role.pro': 'Professional',
            'header.role.client': 'Client',

            'clients.title': 'Client Management',
            'clients.subtitle': 'Directory of your active and inactive trainees.',
            'clients.invite': 'Invite New Client',
            'clients.search': 'Search clients...',
            'clients.filter': 'Filter',
            'clients.table.client': 'Client',
            'clients.table.plan': 'Active Plan',
            'clients.table.compliance': 'Compliance',
            'clients.table.checkin': 'Last Check-in',
            'clients.table.status': 'Status',
            'clients.table.actions': 'Actions',
            'clients.modal.delete.title': 'Delete Client?',
            'clients.modal.delete.cancel': 'Cancel',
            'clients.modal.delete.confirm': 'Delete Client',
            'clients.invite.title': 'Invite New Client',
            'clients.invite.subtitle': "Send an invitation email to your client. They'll receive a link to create their ShapeUp account and connect with you.",
            'clients.invite.label': 'Client Email Address',
            'clients.invite.placeholder': 'client@example.com',
            'clients.invite.btn.cancel': 'Cancel',
            'clients.invite.btn.send': 'Send Invite',
            'clients.invite.error.empty': 'Please enter an email address.',
            'clients.invite.error.invalid': 'Please enter a valid email address.',
            'clients.invite.success.title': 'Invite Sent!',
            'clients.invite.success.desc': "An invitation has been sent to {{email}}. They'll receive an email with a link to join your coaching program.",
            'clients.invite.success.btn': 'Done',

            'clients.status.active': 'Active',
            'clients.status.attention': 'Needs Attention',
            'clients.status.invited': 'Invited',
            'clients.status.inactive': 'Inactive',
            'pro.training.title.builder': 'Plan Builder',
            'pro.training.title.library': 'Training Library',
            'pro.training.subtitle.builder': 'Build reusable training templates and analyze structural volume.',
            'pro.training.subtitle.library': 'Manage your training templates and assign them to clients.',
            'pro.training.btn.create': 'Create New Plan',
            'pro.training.btn.back': 'Back to Library',
            'pro.training.empty.title': 'Your Template Library is Empty',
            'pro.training.empty.desc': 'Create reusable workout templates to easily assign structured training blocks to your clients.',
            'pro.training.empty.btn': 'Create First Plan',
            'pro.training.card.exercises': 'Exercises',
            'pro.training.card.sets': 'Sets',
            'pro.training.card.time': 'Est. Time',
            'pro.training.card.btn.edit': 'Edit Template',
            'pro.training.card.btn.assign': 'Assign to Client',
            'pro.training.assign.modal.title': 'Assign to Client',
            'pro.training.assign.modal.desc': 'Select a client to assign this template to:',
            'pro.training.assign.empty': 'No active clients found.',
            'pro.training.assign.success.title': 'Template Assigned',
            'pro.training.assign.success.message': 'The template has been successfully assigned to the client.',
            'pro.training.assign.success.btn': 'Great!',
            'pro.exercises.title': 'Exercise Library',
            'pro.exercises.subtitle': 'Browse and manage the global exercise database.',
            'pro.exercises.btn.suggest': 'Suggest New Exercise',
            'pro.exercises.search': 'Search exercises by name...',
            'pro.exercises.filter': 'Muscles',
            'pro.exercises.filter.header': 'Filter by Target Muscle',
            'pro.exercises.filter.clear': 'Clear Filters',
            'pro.exercises.empty': 'No exercises found matching your criteria.',

            'pro.feedback.title': 'Feedback & Inbox',
            'pro.feedback.subtitle': 'Review client check-ins, form videos, and direct messages.',
            'pro.feedback.search': 'Search messages...',
            'pro.feedback.empty.list': 'No messages yet.',
            'pro.feedback.ticket.action': 'Action Required',
            'pro.feedback.ticket.needs': 'Needs Attention: ',
            'pro.feedback.ticket.general': 'General Chat',
            'pro.feedback.btn.resolve': 'Mark Resolved',
            'pro.feedback.unread.new': 'New Messages Below',
            'pro.feedback.replying': 'Replying to ',
            'pro.feedback.you': 'You',
            'pro.feedback.attachment.doc': 'Message attachment',
            'pro.feedback.input.placeholder': 'Reply to ',
            'pro.feedback.input.btn': 'Send Reply',
            'pro.feedback.empty.thread.title': 'No Message Selected',
            'pro.feedback.empty.thread.desc': 'Select a conversation from the active feed to view details.',
            'pro.feedback.menu.reply': 'Reply to Message',

            'pro.analytics.title': 'Business Analytics',
            'pro.analytics.subtitle': 'Track your coaching business growth and overall client performance.',
            'pro.analytics.btn.export': 'Export Report',
            'pro.analytics.metric.mrr': 'Monthly Recurring Revenue',
            'pro.analytics.metric.mrr.trend': 'Based on Current Subscriptions',
            'pro.analytics.metric.clients': 'Active Clients',
            'pro.analytics.metric.clients.trend': 'Real-time Rosters',
            'pro.analytics.metric.adherence': 'Global Adherence',
            'pro.analytics.metric.adherence.trend': 'Computed from Active P.',
            'pro.analytics.metric.lifespan': 'Avg. Client Lifespan',
            'pro.analytics.metric.lifespan.unit': 'mo',
            'pro.analytics.metric.lifespan.trend': 'Stable',
            'pro.analytics.chart.growth': 'Client Growth & Retention',
            'pro.analytics.chart.growth.active': 'Active Clients',
            'pro.analytics.chart.growth.churned': 'Churned',
            'pro.analytics.chart.adherence': 'Adherence Distribution',
            'pro.analytics.chart.adherence.clients': 'Clients',

            'pro.client.btn.message': 'Message Client',
            'pro.client.tabs.analytics': 'Analytics',
            'pro.client.tabs.plans': 'Training Plans',
            'pro.client.empty.analytics.title': 'No Data Available',
            'pro.client.empty.analytics.desc': "This client hasn't recorded any workout sessions yet. Analytics will appear once they complete a session.",
            'pro.client.chart.volume': 'Session Volume Trend',
            'pro.client.chart.rpe': 'Session RPE Trend (Effort)',
            'pro.client.chart.weight': 'Bodyweight Trend',
            'pro.client.chart.weight.empty': 'The client needs to log at least 2 weight entries in their Objectives tab to generate this trend.',
            'pro.client.chart.adherence': 'Adherence (Last 30 Days)',
            'pro.client.adherence.completed': 'Completed',
            'pro.client.adherence.skipped': 'Skipped',
            'pro.client.adherence.partial': 'Partial',
            'pro.client.chart.prs': 'Recent PRs & Improvements',
            'pro.client.prs.empty': 'No records broken yet.',
            'pro.client.plan.active': 'Active',
            'pro.client.plan.weeks': 'weeks',
            'pro.client.plan.exercises': 'exercises',
            'pro.client.plan.btn.edit': 'Edit',
            'pro.client.plan.btn.copy': 'Copy',
            'pro.client.plan.empty.ex': 'No exercises yet — click Edit to add some',
            'pro.client.plan.history.hide': 'Hide session history',
            'pro.client.plan.history.show': 'Show session history',
            'pro.client.plan.history.tag.partial': 'Partial',
            'pro.client.plan.history.tag.skipped.sess': 'Skipped Session',
            'pro.client.plan.history.tag.skipped.ex': 'Skipped Exercise',
            'pro.client.plan.delete.title': 'Delete Plan?',
            'pro.client.plan.delete.desc': 'will be permanently removed. This action cannot be undone.',
            'pro.client.plan.delete.cancel': 'Cancel',
            'pro.client.plan.delete.confirm': 'Delete Plan',
            'pro.client.plans.title': 'Assigned Plans',
            'pro.client.plans.btn.add': 'Add Plan',
            'pro.client.plans.empty': 'No plans assigned yet. Click "Add Plan" to create one.',

            'pro.builder.name': 'Plan Name',
            'pro.builder.weeks': 'Duration (Weeks)',
            'pro.builder.phase': 'Phase / Objective',
            'pro.builder.diff': 'Difficulty',
            'pro.builder.notes': 'General Plan Notes',
            'pro.builder.notes.ph': 'e.g. Focus on progressive overload over 6 weeks...',
            'pro.builder.stack': 'Exercise Stack',
            'pro.builder.add.ex': 'Add Exercise',
            'pro.builder.ex.name.ph': 'Exercise name',
            'pro.builder.ex.tags.ph': 'Tags e.g. Chest • Compound',
            'pro.builder.ex.notes.ph': 'Execution notes...',
            'pro.builder.set.type': 'Type',
            'pro.builder.set.tech': 'Technique',
            'pro.builder.set.reps': 'Reps',
            'pro.builder.set.load': 'Load %',
            'pro.builder.set.rpe': 'RPE',
            'pro.builder.set.rest': 'Rest (s)',
            'pro.builder.add.set': 'Add Set',
            'pro.builder.error.title': 'Duplicate Exercise',
            'pro.builder.error.duplicate': 'This exercise is already in the plan.',
            'pro.builder.error.btn': 'I Understand',
            'pro.builder.summary.title': 'Plan Summary',
            'pro.builder.summary.ex': 'Total Exercises',
            'pro.builder.summary.sets': 'Total Sets',
            'pro.builder.summary.sets.val': 'sets',
            'pro.builder.summary.time': 'Est. Duration',
            'pro.builder.summary.rpe': 'Avg RPE Target',
            'pro.builder.summary.phase': 'Phase',
            'pro.builder.summary.diff': 'Difficulty',
            'pro.builder.chart.intensity': 'Intensity Distribution',
            'pro.builder.chart.tech': 'Technique Usage',
            'pro.builder.btn.save': 'Save Plan',
            'pro.builder.btn.assign': 'Assign to Client',
            'pro.builder.btn.cancel': 'Cancel',

            'client.dashboard.welcome': 'Welcome back,',
            'client.dashboard.subtitle.nodata': 'Go to My Training to start your first session!',
            'client.dashboard.metric.weekly': 'Weekly Volume',
            'client.dashboard.metric.streak': 'Current Streak',
            'client.dashboard.metric.sessions': 'Sessions Completed',
            'client.dashboard.trend.weekly.nosessions': 'No sessions yet',
            'client.dashboard.trend.weekly.first': 'First week!',
            'client.dashboard.trend.streak.start': 'Start your streak!',
            'client.dashboard.trend.streak.great': '🔥 Great consistency!',
            'client.dashboard.trend.streak.keep': 'Keep it up!',
            'client.dashboard.trend.sessions.noplans': 'No plans assigned yet',
            'client.dashboard.trend.sessions.plans': 'Training plans',
            'client.dashboard.chart.title': 'Volume Progression',
            'client.dashboard.chart.nodata': 'Complete at least 2 sessions to see your volume trend.',
            'client.dashboard.achievements.title': 'Recent Improvements',
            'client.dashboard.achievements.nodata': 'Keep training and your improvements will appear here!',

            'client.training.title': 'Your Training Plans',
            'client.training.empty.title': 'No Plans Assigned',
            'client.training.empty.desc': "You don't have any training plans assigned to you yet.",
            'client.training.card.difficulty': 'Difficulty',
            'client.training.card.weeks': 'weeks',
            'client.training.card.exercises': 'Exercises',
            'client.training.card.btn': 'Start Session',
            'client.training.history.title': 'Session History',
            'client.training.history.empty': 'No completed sessions yet. Start a workout to build your history!',
            'client.training.history.vol': 'vol',
            'client.training.pagination.prev': 'Previous',
            'client.training.pagination.page': 'Page',
            'client.training.pagination.of': 'of',
            'client.training.pagination.next': 'Next',

            'client.objectives.title': 'Your Objectives',
            'client.objectives.target.title': 'Target Goal',
            'client.objectives.target.label': 'Goal Weight (kg)',
            'client.objectives.target.btn': 'Update Goal',
            'client.objectives.target.saved': 'Goal Saved!',
            'client.objectives.log.title': 'Log Today\'s Weight',
            'client.objectives.log.label': "Today's Weight (kg)",
            'client.objectives.log.btn': 'Log Weight',
            'client.objectives.history.title': 'History',
            'client.objectives.history.empty': 'No weight entries logged yet.',
            'client.objectives.chart.title': 'Bodyweight Trend',

            'client.objectives.chart.empty': 'Log at least 2 weight entries to see your trend chart.',

            'settings.title': 'Settings',
            'settings.subtitle.pro': 'Manage your professional coaching profile and subscription.',
            'settings.subtitle.client': 'Update your personal details and app preferences.',
            'settings.tabs.profile': 'Profile & Brand',
            'settings.tabs.profile_client': 'Account Details',
            'settings.tabs.notifications': 'Notifications',
            'settings.tabs.preferences': 'App Preferences',
            'settings.tabs.billing': 'Billing & Plan',
            'settings.tabs.integrations': 'Integrations',
            'settings.tabs.coach': 'My Coach',
            'preferences.title': 'App Preferences',
            'preferences.theme.title': 'Appearance (Theme)',
            'preferences.theme.desc': 'Toggle between Light and Dark mode globally.',
            'preferences.theme.light': 'Switch to Light',
            'preferences.theme.dark': 'Switch to Dark',
            'preferences.lang.title': 'Language',
            'preferences.lang.desc': 'Select your preferred display language.',
            'preferences.units.title': 'Measurement Units',
            'preferences.units.desc': 'Choose between Metric (kg/cm) and Imperial (lbs/in).',

            'reports.title': 'Reports & Exports',
            'reports.subtitle': 'Generate custom data exports for billing, adherence, and client history.',
            'reports.generator.title': 'Create New Report',
            'reports.form.type': 'Report Type',
            'reports.type.performance': 'Overall Roster Performance & Adherence',
            'reports.type.billing': 'Billing & Revenue Summary',
            'reports.type.history': 'Specific Client History (Workouts & Logs)',
            'reports.form.scope': 'Target Scope',
            'reports.scope.all': 'All Active Clients',
            'reports.scope.specific': 'Specific Client...',
            'reports.form.client': 'Select Client',
            'reports.form.client.placeholder': 'Choose a client...',
            'reports.form.range': 'Date Range',
            'reports.range.30days': 'Last 30 Days',
            'reports.range.lastmonth': 'Last Month',
            'reports.range.ytd': 'Year to Date (YTD)',
            'reports.range.custom': 'Custom Range...',
            'reports.form.start': 'Start Date',
            'reports.form.end': 'End Date',
            'reports.form.format': 'Export Format',
            'reports.format.pdf': 'PDF Document',
            'reports.format.csv': 'CSV / Excel',
            'reports.btn.generate': 'Generate Report',
            'reports.btn.generating': 'Generating...',
            'reports.help.wait': 'Please wait, preparing your document...',
            'reports.help.ready': 'Generation usually takes 1-2 seconds.',
            'reports.history.title': 'Recent Reports',
            'reports.history.view_all': 'View All',
            'reports.history.empty': 'No reports generated yet.',
            'reports.history.col.name': 'Report Name',
            'reports.history.col.type': 'Type',
            'reports.history.col.date': 'Generated',
            'reports.history.col.status': 'Status',
            'reports.history.col.actions': 'Actions',
            'reports.history.btn.download': 'Download',
            'reports.history.status.completed': 'Completed',
            'reports.warning.scope.title': 'Specific Scope Required:',
            'reports.warning.scope.desc': 'Client history reports can only be generated for a single specific client. Please change the Target Scope above.',

            'client.chat.title': 'Coach Alex',
            'client.chat.status.online': 'Online',
            'client.chat.input.placeholder': 'Message Coach...',
            'client.chat.input.editing': 'Editing message...',
            'client.chat.replying': 'Replying to ',
            'client.chat.you': 'You',
            'client.chat.coach': 'Coach',
            'client.chat.edited': '(edited)',
            'client.chat.menu.reply': 'Reply to Message',
            'client.chat.tag.general': 'General',
            'client.chat.tag.form_check': 'Form Check',
            'client.chat.tag.rpe_report': 'RPE Report',
            'client.chat.tag.question': 'Question',
            'client.chat.tag.checkin': 'Check-in'
        },
        'pt-BR': {
            'nav.dashboard': 'Painel',
            'nav.clients': 'Clientes',
            'nav.training_plans': 'Planos de Treino',
            'nav.my_training': 'Meus Treinos',
            'nav.exercises_library': 'Biblioteca de Exercícios',
            'nav.reports': 'Relatórios',
            'nav.feedback': 'E-mail / Dúvidas',
            'nav.analytics': 'Analítica',
            'nav.settings': 'Configurações',
            'nav.objectives': 'Objetivos',
            'sidebar.chat': 'Falar com Treinador',

            'pro.dashboard.title': 'Visão Geral do Painel',
            'pro.dashboard.subtitle': 'Veja o que está acontecendo com seus clientes hoje.',
            'pro.dashboard.invite': 'Convidar Cliente',
            'pro.dashboard.metric.active': 'Clientes Ativos',
            'pro.dashboard.metric.active.sub': 'Portfólio Ativo Total',
            'pro.dashboard.metric.completed': 'Treinos Concluídos',
            'pro.dashboard.metric.completed.sub': 'Volume Global 30 dias',
            'pro.dashboard.metric.skipped': 'Treinos Pulados',
            'pro.dashboard.metric.skipped.sub': 'Precisa de Atenção',
            'pro.dashboard.metric.engagement': 'Engajamento Médio',
            'pro.dashboard.metric.engagement.sub': 'Adesão à Plataforma',

            'pro.dashboard.feed.title': 'Feed de Atividades Global',
            'pro.dashboard.search': 'Buscar...',
            'pro.dashboard.filter.all': 'Todas as Entradas',
            'pro.dashboard.filter.workout': 'Treinos',
            'pro.dashboard.filter.message': 'Mensagens',
            'pro.dashboard.filter.alert': 'Alertas',
            'pro.dashboard.filter.system': 'Sistema',
            'pro.dashboard.btn.clear': 'Limpar',
            'pro.dashboard.feed.empty': 'Nenhuma atividade encontrada com estes filtros.',
            'pro.dashboard.feed.page': 'Página',
            'pro.dashboard.feed.of': 'de',
            'pro.dashboard.alerts.title': 'Alertas de Clientes',
            'pro.dashboard.alerts.empty': 'Todos os clientes estão no caminho certo.',
            'sidebar.logout': 'Sair',
            'header.role.pro': 'Profissional',
            'header.role.client': 'Cliente',

            'clients.title': 'Gestão de Clientes',
            'clients.subtitle': 'Diretório dos seus alunos ativos e inativos.',
            'clients.invite': 'Convidar Novo Cliente',
            'clients.search': 'Buscar clientes...',
            'clients.filter': 'Filtrar',
            'clients.table.client': 'Cliente',
            'clients.table.plan': 'Plano Ativo',
            'clients.table.compliance': 'Adesão',
            'clients.table.checkin': 'Último Check-in',
            'clients.table.status': 'Status',
            'clients.table.actions': 'Ações',
            'clients.modal.delete.title': 'Excluir Cliente?',
            'clients.modal.delete.cancel': 'Cancelar',
            'clients.modal.delete.confirm': 'Excluir Cliente',
            'clients.invite.title': 'Convidar Novo Cliente',
            'clients.invite.subtitle': 'Envie um e-mail de convite para seu cliente. Eles receberão um link para criar sua conta no ShapeUp e se conectar com você.',
            'clients.invite.label': 'E-mail do Cliente',
            'clients.invite.placeholder': 'cliente@exemplo.com',
            'clients.invite.btn.cancel': 'Cancelar',
            'clients.invite.btn.send': 'Enviar Convite',
            'clients.invite.error.empty': 'Por favor, insira um endereço de e-mail.',
            'clients.invite.error.invalid': 'Por favor, insira um endereço de e-mail válido.',
            'clients.invite.success.title': 'Convite Enviado!',
            'clients.invite.success.desc': 'Um convite foi enviado para {{email}}. Eles receberão um e-mail com um link para participar do seu programa de treinamento.',
            'clients.invite.success.btn': 'Concluído',

            'clients.status.active': 'Ativo',
            'clients.status.attention': 'Precisa de Atenção',
            'clients.status.invited': 'Convidado',
            'clients.status.inactive': 'Inativo',
            'pro.training.title.builder': 'Construtor de Planos',
            'pro.training.title.library': 'Biblioteca de Treinos',
            'pro.training.subtitle.builder': 'Crie modelos de treinos reutilizáveis e analise o volume.',
            'pro.training.subtitle.library': 'Gerencie seus modelos de treino e atribua aos clientes.',
            'pro.training.btn.create': 'Criar Novo Plano',
            'pro.training.btn.back': 'Voltar para Biblioteca',
            'pro.training.empty.title': 'Sua Biblioteca de Modelos está Vazia',
            'pro.training.empty.desc': 'Crie modelos de treino reutilizáveis para atribuí-los facilmente aos seus clientes.',
            'pro.training.empty.btn': 'Criar Primeiro Plano',
            'pro.training.card.exercises': 'Exercícios',
            'pro.training.card.sets': 'Séries',
            'pro.training.card.time': 'Tempo Est.',
            'pro.training.card.btn.edit': 'Editar Modelo',
            'pro.training.card.btn.assign': 'Atribuir a Cliente',
            'pro.training.assign.modal.title': 'Atribuir a Cliente',
            'pro.training.assign.modal.desc': 'Selecione um cliente para atribuir este modelo:',
            'pro.training.assign.empty': 'Nenhum cliente ativo encontrado.',
            'pro.training.assign.success.title': 'Modelo Atribuído',
            'pro.training.assign.success.message': 'O modelo foi atribuído com sucesso ao cliente.',
            'pro.training.assign.success.btn': 'Ótimo!',
            'pro.exercises.title': 'Biblioteca de Exercícios',
            'pro.exercises.subtitle': 'Navegue e gerencie o banco de dados global de exercícios.',
            'pro.exercises.btn.suggest': 'Sugerir Novo Exercício',
            'pro.exercises.search': 'Buscar exercícios por nome...',
            'pro.exercises.filter': 'Músculos',
            'pro.exercises.filter.header': 'Filtrar por Músculo Alvo',
            'pro.exercises.filter.clear': 'Limpar Filtros',
            'pro.exercises.empty': 'Nenhum exercício encontrado com esses critérios.',

            'pro.feedback.title': 'Feedback & Mensagens',
            'pro.feedback.subtitle': 'Revise check-ins, vídeos de execução e mensagens diretas.',
            'pro.feedback.search': 'Buscar mensagens...',
            'pro.feedback.empty.list': 'Nenhuma mensagem ainda.',
            'pro.feedback.ticket.action': 'Ação Necessária',
            'pro.feedback.ticket.needs': 'Atenção Necessária: ',
            'pro.feedback.ticket.general': 'Chat Geral',
            'pro.feedback.btn.resolve': 'Marcar como Resolvido',
            'pro.feedback.unread.new': 'Novas Mensagens Abaixo',
            'pro.feedback.replying': 'Respondendo a ',
            'pro.feedback.you': 'Você',
            'pro.feedback.attachment.doc': 'Anexo da Mensagem',
            'pro.feedback.input.placeholder': 'Responder para ',
            'pro.feedback.input.btn': 'Enviar Resposta',
            'pro.feedback.empty.thread.title': 'Nenhuma Mensagem Selecionada',
            'pro.feedback.empty.thread.desc': 'Selecione uma conversa do feed para visualizar os detalhes.',
            'pro.feedback.menu.reply': 'Responder Mensagem',

            'pro.analytics.title': 'Análises de Negócio',
            'pro.analytics.subtitle': 'Acompanhe o crescimento do seu negócio e o desempenho geral dos clientes.',
            'pro.analytics.btn.export': 'Exportar Relatório',
            'pro.analytics.metric.mrr': 'Receita Mensal Recorrente',
            'pro.analytics.metric.mrr.trend': 'Baseado nas Assinaturas Atuais',
            'pro.analytics.metric.clients': 'Clientes Ativos',
            'pro.analytics.metric.clients.trend': 'Listas em Tempo Real',
            'pro.analytics.metric.adherence': 'Adesão Global',
            'pro.analytics.metric.adherence.trend': 'Calculado sobre P. Ativos',
            'pro.analytics.metric.lifespan': 'Tempo Médio de Vida do Cliente',
            'pro.analytics.metric.lifespan.unit': 'm',
            'pro.analytics.metric.lifespan.trend': 'Estável',
            'pro.analytics.chart.growth': 'Crescimento e Retenção de Clientes',
            'pro.analytics.chart.growth.active': 'Clientes Ativos',
            'pro.analytics.chart.growth.churned': 'Cancelados',
            'pro.analytics.chart.adherence': 'Distribuição de Adesão',
            'pro.analytics.chart.adherence.clients': 'Clientes',

            'pro.client.btn.message': 'Enviar Mensagem',
            'pro.client.tabs.analytics': 'Análise',
            'pro.client.tabs.plans': 'Planos de Treino',
            'pro.client.empty.analytics.title': 'Sem Dados Disponíveis',
            'pro.client.empty.analytics.desc': 'Este cliente ainda não registrou nenhum treino. As análises aparecerão quando ele completar uma sessão.',
            'pro.client.chart.volume': 'Tendência de Volume',
            'pro.client.chart.rpe': 'Tendência de RPE (Esforço)',
            'pro.client.chart.weight': 'Tendência de Peso',
            'pro.client.chart.weight.empty': 'O cliente precisa registrar pelo menos 2 pesos na aba Objetivos para gerar esta tendência.',
            'pro.client.chart.adherence': 'Adesão (Últimos 30 Dias)',
            'pro.client.adherence.completed': 'Concluído',
            'pro.client.adherence.skipped': 'Pulado',
            'pro.client.adherence.partial': 'Parcial',
            'pro.client.chart.prs': 'Recordes Pessoais Recentes',
            'pro.client.prs.empty': 'Nenhum recorde quebrado ainda.',
            'pro.client.plan.active': 'Ativo',
            'pro.client.plan.weeks': 'semanas',
            'pro.client.plan.exercises': 'exercícios',
            'pro.client.plan.btn.edit': 'Editar',
            'pro.client.plan.btn.copy': 'Copiar',
            'pro.client.plan.empty.ex': 'Nenhum exercício ainda — clique em Editar para adicionar',
            'pro.client.plan.history.hide': 'Ocultar histórico',
            'pro.client.plan.history.show': 'Mostrar histórico',
            'pro.client.plan.history.tag.partial': 'Parcial',
            'pro.client.plan.history.tag.skipped.sess': 'Sessão Pulada',
            'pro.client.plan.history.tag.skipped.ex': 'Exercício Pulado',
            'pro.client.plan.delete.title': 'Excluir Plano?',
            'pro.client.plan.delete.desc': 'será permanentemente removido. Esta ação não pode ser desfeita.',
            'pro.client.plan.delete.cancel': 'Cancelar',
            'pro.client.plan.delete.confirm': 'Excluir Plano',
            'pro.client.plans.title': 'Planos Atribuídos',
            'pro.client.plans.btn.add': 'Adicionar Plano',
            'pro.client.plans.empty': 'Nenhum plano atribuído. Clique em "Adicionar Plano" para criar um.',

            'pro.builder.name': 'Nome do Plano',
            'pro.builder.weeks': 'Duração (Semanas)',
            'pro.builder.phase': 'Fase / Objetivo',
            'pro.builder.diff': 'Dificuldade',
            'pro.builder.notes': 'Notas Gerais',
            'pro.builder.notes.ph': 'ex: Foco em sobrecarga progressiva ao longo de 6 semanas...',
            'pro.builder.stack': 'Pilha de Exercícios',
            'pro.builder.add.ex': 'Adicionar Exercício',
            'pro.builder.ex.name.ph': 'Nome do exercício',
            'pro.builder.ex.tags.ph': 'Tags ex: Peito • Composto',
            'pro.builder.ex.notes.ph': 'Notas de execução...',
            'pro.builder.set.type': 'Tipo',
            'pro.builder.set.tech': 'Técnica',
            'pro.builder.set.reps': 'Reps',
            'pro.builder.set.load': 'Carga %',
            'pro.builder.set.rpe': 'RPE',
            'pro.builder.set.rest': 'Descanso (s)',
            'pro.builder.add.set': 'Adicionar Série',
            'pro.builder.error.title': 'Exercício Duplicado',
            'pro.builder.error.duplicate': 'Este exercício já está no plano.',
            'pro.builder.error.btn': 'Entendido',
            'pro.builder.summary.title': 'Resumo do Plano',
            'pro.builder.summary.ex': 'Total de Exercícios',
            'pro.builder.summary.sets': 'Total de Séries',
            'pro.builder.summary.sets.val': 'séries',
            'pro.builder.summary.time': 'Tempo Est.',
            'pro.builder.summary.rpe': 'RPE Médio Alvo',
            'pro.builder.summary.phase': 'Fase',
            'pro.builder.summary.diff': 'Dificuldade',
            'pro.builder.chart.intensity': 'Distribuição de Intensidade',
            'pro.builder.chart.tech': 'Uso de Técnica',
            'pro.builder.btn.save': 'Salvar Plano',
            'pro.builder.btn.assign': 'Atribuir ao Cliente',
            'pro.builder.btn.cancel': 'Cancelar',

            'client.dashboard.welcome': 'Bem-vindo de volta,',
            'client.dashboard.subtitle.nodata': 'Vá para Meus Treinos para começar sua primeira sessão!',
            'client.dashboard.metric.weekly': 'Volume Semanal',
            'client.dashboard.metric.streak': 'Dias Consecutivos',
            'client.dashboard.metric.sessions': 'Sessões Concluídas',
            'client.dashboard.trend.weekly.nosessions': 'Nenhuma sessão ainda',
            'client.dashboard.trend.weekly.first': 'Primeira semana!',
            'client.dashboard.trend.streak.start': 'Comece seu ritmo!',
            'client.dashboard.trend.streak.great': '🔥 Ótima consistência!',
            'client.dashboard.trend.streak.keep': 'Continue assim!',
            'client.dashboard.trend.sessions.noplans': 'Nenhum plano atribuído',
            'client.dashboard.trend.sessions.plans': 'Planos de treino',
            'client.dashboard.chart.title': 'Progressão de Volume',
            'client.dashboard.chart.nodata': 'Complete pelo menos 2 sessões para ver sua tendência.',
            'client.dashboard.achievements.title': 'Evoluções Recentes',
            'client.dashboard.achievements.nodata': 'Continue treinando e suas evoluções aparecerão aqui!',

            'client.training.title': 'Seus Planos de Treino',
            'client.training.empty.title': 'Nenhum Plano Atribuído',
            'client.training.empty.desc': 'Você não tem nenhum plano de treino atribuído a você ainda.',
            'client.training.card.difficulty': 'Dificuldade',
            'client.training.card.weeks': 'semanas',
            'client.training.card.exercises': 'Exercícios',
            'client.training.card.btn': 'Iniciar Sessão',
            'client.training.history.title': 'Histórico de Sessões',
            'client.training.history.empty': 'Nenhuma sessão concluída ainda. Inicie um treino para construir seu histórico!',
            'client.training.history.vol': 'vol',
            'client.training.pagination.prev': 'Anterior',
            'client.training.pagination.page': 'Página',
            'client.training.pagination.of': 'de',
            'client.training.pagination.next': 'Próximo',

            'client.objectives.title': 'Seus Objetivos',
            'client.objectives.target.title': 'Meta Alvo',
            'client.objectives.target.label': 'Peso Meta (kg)',
            'client.objectives.target.btn': 'Atualizar Meta',
            'client.objectives.target.saved': 'Meta Salva!',
            'client.objectives.log.title': 'Registrar Peso de Hoje',
            'client.objectives.log.label': 'Peso de Hoje (kg)',
            'client.objectives.log.btn': 'Registrar Peso',
            'client.objectives.history.title': 'Histórico',
            'client.objectives.history.empty': 'Nenhum peso registrado ainda.',
            'client.objectives.chart.title': 'Tendência de Peso Corporal',
            'client.objectives.chart.empty': 'Registre pelo menos 2 pesos para ver seu gráfico de tendência.',

            'settings.title': 'Configurações',
            'settings.subtitle.pro': 'Gerencie seu perfil profissional e assinatura.',
            'settings.subtitle.client': 'Atualize seus detalhes pessoais e preferências do app.',
            'settings.tabs.profile': 'Perfil e Marca',
            'settings.tabs.profile_client': 'Detalhes da Conta',
            'settings.tabs.notifications': 'Notificações',
            'settings.tabs.preferences': 'Preferências do App',
            'settings.tabs.billing': 'Faturamento e Plano',
            'settings.tabs.integrations': 'Integrações',
            'settings.tabs.coach': 'Meu Treinador',
            'preferences.title': 'Preferências do App',
            'preferences.theme.title': 'Aparência (Tema)',
            'preferences.theme.desc': 'Alterne entre o modo Claro e Escuro globalmente.',
            'preferences.theme.light': 'Mudar para Claro',
            'preferences.theme.dark': 'Mudar para Escuro',
            'preferences.lang.title': 'Idioma',
            'preferences.lang.desc': 'Selecione o idioma de exibição de sua preferência.',
            'preferences.units.title': 'Unidades de Medida',
            'preferences.units.desc': 'Escolha entre Métrico (kg/cm) e Imperial (lbs/in).',

            'reports.title': 'Relatórios & Exportações',
            'reports.subtitle': 'Gere exportações de dados personalizadas para faturamento, adesão e histórico do cliente.',
            'reports.generator.title': 'Criar Novo Relatório',
            'reports.form.type': 'Tipo de Relatório',
            'reports.type.performance': 'Desempenho Geral e Adesão do Elenco',
            'reports.type.billing': 'Resumo de Faturamento e Receita',
            'reports.type.history': 'Histórico Específico do Cliente (Treinos e Logs)',
            'reports.form.scope': 'Escopo Alvo',
            'reports.scope.all': 'Todos os Clientes Ativos',
            'reports.scope.specific': 'Cliente Específico...',
            'reports.form.client': 'Selecionar Cliente',
            'reports.form.client.placeholder': 'Escolha um cliente...',
            'reports.form.range': 'Intervalo de Datas',
            'reports.range.30days': 'Últimos 30 Dias',
            'reports.range.lastmonth': 'Mês Passado',
            'reports.range.ytd': 'Ano até a Data (YTD)',
            'reports.range.custom': 'Intervalo Personalizado...',
            'reports.form.start': 'Data de Início',
            'reports.form.end': 'Data de Término',
            'reports.form.format': 'Formato de Exportação',
            'reports.format.pdf': 'Documento PDF',
            'reports.format.csv': 'CSV / Excel',
            'reports.btn.generate': 'Gerar Relatório',
            'reports.btn.generating': 'Gerando...',
            'reports.help.wait': 'Por favor aguarde, preparando seu documento...',
            'reports.help.ready': 'A geração leva geralmente 1-2 segundos.',
            'reports.history.title': 'Relatórios Recentes',
            'reports.history.view_all': 'Ver Tudo',
            'reports.history.empty': 'Nenhum relatório gerado ainda.',
            'reports.history.col.name': 'Nome do Relatório',
            'reports.history.col.type': 'Tipo',
            'reports.history.col.date': 'Gerado em',
            'reports.history.col.status': 'Status',
            'reports.history.col.actions': 'Ações',
            'reports.history.btn.download': 'Baixar',
            'reports.history.status.completed': 'Concluído',
            'reports.warning.scope.title': 'Escopo Específico Necessário:',
            'reports.warning.scope.desc': 'Relatórios de histórico do cliente só podem ser gerados para um único cliente específico. Por favor, altere o Escopo Alvo acima.',

            'client.chat.title': 'Treinador Alex',
            'client.chat.status.online': 'Online',
            'client.chat.input.placeholder': 'Falar com Treinador...',
            'client.chat.input.editing': 'Editando mensagem...',
            'client.chat.replying': 'Respondendo a ',
            'client.chat.you': 'Você',
            'client.chat.coach': 'Treinador',
            'client.chat.edited': '(editado)',
            'client.chat.menu.reply': 'Responder Mensagem',
            'client.chat.tag.general': 'Geral',
            'client.chat.tag.form_check': 'Análise de Técnica',
            'client.chat.tag.rpe_report': 'Relato de Esforço',
            'client.chat.tag.question': 'Dúvida',
            'client.chat.tag.checkin': 'Check-in'
        }
    };

    const t = (key) => {
        return translations[language]?.[key] || translations['en'][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
