import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useLanguage } from '../contexts/LanguageContext';
export default function ClientPortfolio({ clients }) {
  const { language } = useLanguage(); const pt = language === 'pt-BR';
  const [filter, setFilter] = useState('all');
  const overdue = client => Number(client.compliance || 0) < 50;
  const review = client => !client.activePlan || client.activePlan === '-';
  const filtered = clients.filter(client => filter === 'all' || (filter === 'overdue' ? overdue(client) : review(client)));
  return <section className="su-portfolio su-portfolio-editorial"><header><div><h2>{pt ? 'Carteira de alunos & status semanal' : 'Athletes & weekly status'}</h2><p>{pt ? 'Visão rápida de execução, consistência e ciclo vigente.' : 'Training, consistency and current cycle.'}</p></div><div className="su-portfolio-tabs">{[['all', pt ? 'Todos' : 'All', clients.length], ['overdue', pt ? 'Atrasados' : 'Overdue', clients.filter(overdue).length], ['review', pt ? 'Revisão' : 'Review', clients.filter(review).length]].map(([id, label, count]) => <button key={id} type="button" aria-pressed={filter === id} onClick={() => setFilter(id)}>{label} <small>({count})</small></button>)}</div></header>
    <div className="su-portfolio-scroll"><table><thead><tr><th>{pt ? 'Aluno & objetivo' : 'Athlete & goal'}</th><th>{pt ? 'Último treino' : 'Last session'}</th><th>{pt ? 'Freq. semanal' : 'Weekly adherence'}</th><th>{pt ? 'Periodização' : 'Training cycle'}</th><th>{pt ? 'Ações rápidas' : 'Quick actions'}</th></tr></thead><tbody>{filtered.slice(0, 4).map(client => <tr key={client.id} className={overdue(client) ? 'needs-attention' : ''}><td><div className="su-portfolio-person"><span className="su-avatar">{client.avatar ? <img src={client.avatar} alt="" /> : client.name?.split(' ').slice(0,2).map(part=>part[0]).join('')}</span><div><strong>{client.name}</strong><small>{client.goal || client.objective || client.activePlan || '—'}</small></div></div></td><td>{client.lastCheckin || '—'}</td><td><div className="su-portfolio-compliance"><span>{client.compliance ?? 0}%</span><progress max="100" value={Math.max(0, Math.min(100, Number(client.compliance) || 0))} aria-label={pt ? 'Aderência' : 'Adherence'} /></div></td><td><strong>{client.activePlan || '—'}</strong><small>{review(client) ? (pt ? 'Aguardando prescrição' : 'Awaiting prescription') : (pt ? 'Plano ativo' : 'Active plan')}</small></td><td><Link className="su-btn su-btn-secondary" to={`/dashboard/clients/${client.id}`}>{pt ? 'Abrir ficha' : 'Open plan'}</Link></td></tr>)}</tbody></table></div>
    {!filtered.length && <p className="su-portfolio-empty">{clients.length ? (pt ? 'Nenhum aluno neste filtro.' : 'No athletes match this filter.') : (pt ? 'Convide seu primeiro aluno para acompanhar os treinos por aqui.' : 'Invite your first athlete to follow their training here.')}</p>}
    <footer><span>{pt ? `Exibindo ${Math.min(filtered.length,4)} de ${filtered.length} alunos` : `${Math.min(filtered.length,4)} of ${filtered.length} athletes`}</span><Link to="/dashboard/clients">{pt ? 'Ver listagem completa da carteira →' : 'View all athletes →'}</Link></footer></section>;
}
