import { useId, useRef, useState } from 'react';
import { useLanguage } from '../contexts/LanguageContext';

const iso = date => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
const parse = value => /^\d{4}-\d{2}-\d{2}$/.test(value || '') ? new Date(value + 'T12:00:00') : new Date();
const css = `.su-calendar{background:var(--bg-card,#211a17);color:var(--text-main,var(--text-main));border:1px solid var(--border-color,var(--border-color));border-radius:10px;padding:18px;width:320px;max-width:calc(100vw - 32px);max-height:calc(100dvh - 32px);overflow:auto;margin:auto;box-sizing:border-box;font:14px/1.5 sans-serif}.su-calendar::backdrop{background:#0008}.su-calendar button,.su-calendar select{font:inherit;color:inherit;background:transparent;border:1px solid transparent;border-radius:5px;cursor:pointer}.su-calendar select{background:var(--bg-card,#211a17);border-color:var(--border-color,var(--border-color));max-width:145px;padding:5px}.su-calendar button{min-height:36px;min-width:28px}.su-calendar button:hover{background:#e06c4326}.su-calendar button:focus-visible{outline:2px solid #e06c43;outline-offset:2px}.su-calendar button:disabled{opacity:.3;cursor:default}.su-calendar [data-selected=true]{background:#e06c43;color:var(--bg-main)}.su-calendar [aria-current=date]{border-color:#d4a359}.su-calendar-grid{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:3px;text-align:center}.su-calendar-grid small{padding:8px 0;color:var(--text-muted,var(--text-muted))}.su-calendar-head,.su-calendar-foot{display:flex;align-items:center;justify-content:space-between;gap:6px}.su-calendar-foot{margin-top:12px;border-top:1px solid var(--border-color,var(--border-color));padding-top:10px}.su-date-trigger{display:inline-flex;align-items:center;justify-content:space-between;gap:8px;cursor:pointer;max-width:100%;font:inherit}`;

export default function DatePicker({ value, defaultValue = '', onChange, id, name, min, max, disabled, required, iconOnly = false, className = 'su-input', style, 'aria-label': ariaLabel, ...props }) {
  const { language } = useLanguage();
  const text = language === 'en' ? ['Choose date','Previous month','Next month','Today','Clear','Close','Month','Year'] : language === 'es' ? ['Elegir fecha','Mes anterior','Mes siguiente','Hoy','Borrar','Cerrar','Mes','Año'] : ['Escolher data','Mês anterior','Próximo mês','Hoje','Limpar','Fechar','Mês','Ano'];
  const [internal, setInternal] = useState(defaultValue);
  const selected = value ?? internal;
  const [month, setMonth] = useState(() => parse(selected));
  const dialog = useRef(null);
  const trigger = useRef(null);
  const uid = useId();
  const today = iso(new Date());
  const valid = date => (!min || date >= min) && (!max || date <= max);
  const close = () => { dialog.current.close(); trigger.current.focus(); };
  const choose = date => { setInternal(date); onChange?.({ target: { value: date, name, id }, currentTarget: { value: date, name, id } }); close(); };
  const shift = delta => setMonth(date => new Date(date.getFullYear(), date.getMonth() + delta, 1, 12));
  const offset = (new Date(month.getFullYear(), month.getMonth(), 1).getDay() + 6) % 7;
  const count = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate();
  const firstYear = min ? parse(min).getFullYear() : Math.min(1900, month.getFullYear());
  const lastYear = max ? parse(max).getFullYear() : Math.max(new Date().getFullYear() + 20, month.getFullYear());
  return <><style>{css}</style><input type="hidden" name={name || id} value={selected} disabled={disabled} /><button {...props} ref={trigger} id={id} form={`${uid}-trigger-only`} type="button" disabled={disabled} aria-label={ariaLabel || text[0]} aria-haspopup="dialog" aria-controls={uid} className={`su-date-trigger ${className}`} style={style} onClick={() => { setMonth(parse(selected)); dialog.current.showModal(); }}>{!iconOnly && <span>{selected ? parse(selected).toLocaleDateString(language, { day:'2-digit',month:'short',year:'numeric' }) : text[0]}</span>}<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4m10-4v4M3 11h18"/></svg></button><dialog ref={dialog} id={uid} className="su-calendar" aria-label={ariaLabel || text[0]} onClick={event => { if(event.target === dialog.current) { const rect=event.currentTarget.getBoundingClientRect(); if(event.clientX < rect.left || event.clientX > rect.right || event.clientY < rect.top || event.clientY > rect.bottom) close(); } }}>
    <div className="su-calendar-head"><button type="button" aria-label={text[1]} onClick={() => shift(-1)}>‹</button><select aria-label={text[6]} value={month.getMonth()} onChange={event => setMonth(new Date(month.getFullYear(), Number(event.target.value), 1, 12))}>{Array.from({length:12},(_,i)=><option key={i} value={i}>{new Date(2026,i,1).toLocaleDateString(language,{month:'long'})}</option>)}</select><select aria-label={text[7]} value={month.getFullYear()} onChange={event => setMonth(new Date(Number(event.target.value),month.getMonth(),1,12))}>{Array.from({length:lastYear-firstYear+1},(_,i)=><option key={i} value={firstYear+i}>{firstYear+i}</option>)}</select><button type="button" aria-label={text[2]} onClick={() => shift(1)}>›</button></div>
    <div className="su-calendar-grid">{Array.from({length:7},(_,i)=><small key={i}>{new Date(2026,8,7+i).toLocaleDateString(language,{weekday:'short'})}</small>)}{Array.from({length:offset},(_,i)=><span key={`blank-${i}`}/>)}{Array.from({length:count},(_,i)=>{ const date=iso(new Date(month.getFullYear(),month.getMonth(),i+1,12)); return <button type="button" key={date} disabled={!valid(date)} data-date={date} data-selected={selected === date} aria-current={today === date ? 'date' : undefined} aria-label={parse(date).toLocaleDateString(language,{dateStyle:'full'})} onKeyDown={event=>{const delta={ArrowLeft:-1,ArrowRight:1,ArrowUp:-7,ArrowDown:7}[event.key];if(delta){event.preventDefault();const next=parse(date);next.setDate(next.getDate()+delta);if(valid(iso(next))){setMonth(next);requestAnimationFrame(()=>dialog.current.querySelector(`[data-date="${iso(next)}"]`)?.focus());}}}} onClick={()=>choose(date)}>{i+1}</button>; })}</div>
    <div className="su-calendar-foot"><button type="button" disabled={!valid(today)} onClick={()=>choose(today)}>{text[3]}</button>{!required && <button type="button" onClick={()=>choose('')}>{text[4]}</button>}<button type="button" onClick={close}>{text[5]}</button></div>
  </dialog></>;
}
